### ISSUE TITLE
incorrect calculation of a square root

### ISSUE THREAD

**Issue by Skin36** [x64dbg/x64dbg#1009]
http://shot.qip.ru/00knEU-5tfn6TNpw/
http://shot.qip.ru/00knEU-4tfn6TNpx/

**Comment by n1tehawk** [comment]
I'm sorry for falsely having reported this as "abuse" - but creating an issue without any further comment, by simply dropping two links to a russian image hosting site, to me seems a pretty bad practice.

**Comment by mrexodia** [comment]
Yeah my uBlock also didn't want to load the site. As for the issue, could
to code a sample program and show it on a simple example (eg st0=4). There
are many edge cases in fldsqrt and it's probably correct behavior.

It can also be that the result is printed incorrectly.

**Comment by Skin36** [comment]
Sorry, I just wanted to say that "fsqrt" command calculates the square root is not true.

**Comment by mrexodia** [comment]
could you give more details for the bug?

**Comment by Skin36** [comment]
where I can put pictures that you see them?

**Comment by mrexodia** [comment]
I saw the pictures but I don't see an issue here. Maybe the fpu isn't
precise enough or something? You can check the status flags maybe some
information is there.

It's also possible that the values are printed incorrectly but this needs
manual verification.

**Comment by wk-952** [comment]
This seems to be a display issue, it happens when the precision in the FPU control word (`x87CW_PC`) is set to 3 (`Real10`) or 1 (`Not Used`) (the instruction `fninit` sets precision to 3).
![bad](https://cloud.githubusercontent.com/assets/11916365/18000575/0be4e1a6-6b7f-11e6-8894-163744494d44.png)

After manually setting the precision to 2 (`Real8`) or 0 (`Real4`) it was displayed correctly (the program must be restarted to see the effect)
![good](https://cloud.githubusercontent.com/assets/11916365/18000693/8d6d6496-6b7f-11e6-8fa2-c946f91b2c4e.png)

But the value was displayed correctly in the dump window either way.

**Comment by mtomek55** [comment]
I don't think the PC field affects the interpretation (i.e. display) of the x87 register contents. It only changes whether the processor takes the extra bits of mantissa (54-64) into account when executing FSQRT etc. but not FST/FIST. Cf section "Precision Control Field" of IA32 Software Architecture Manual volume 1.
I'm not 100% sure, but I think it is the value itself which causes the problem.

**Comment by mrexodia** [comment]
I tested with https://mega.nz/#!ixRhkT5K!VVqI7wNXKImWdicTqfPvtCxEO9Y0FeHqhCfbRLuKtRE and ollydbg gives the same results as x64dbg now. The only difference is that x64dbg has 1 decimal less precision but the hex values are the same.
