### ISSUE TITLE
Symbols and Exports problems

### ISSUE THREAD

**Issue by webro666** [x64dbg/x64dbg#1056]
Ok, so I have some really weird problems with symbols and exports.

Let's start with symbols:

When I load pdb symbols, i'm not getting undecorated symbols (I do have "Undecorate Symbol Names" checked in the engine options and unchecking it doesn't change anything).

Let's take "ntdll.RtlpAddVectoredHandler":
It's only giving me "_RtlpAddVectoredHandler@12".
The CPU window only shows "_RtlpAddVectoredHandler@12".
The Symbols window only shows "_RtlpAddVectoredHandler@12" ("Symbol (undecorated)" is empty).
The Ctrl+G expression window does not recognize "RtlpAddVectoredHandler" at all (it does recognize "_RtlpAddVectoredHandler@12" though).

Now about exports:

When I don't load pdb symbols, exports are recognized correctly. They are shown in the CPU and Symbols windows and the expression window recognizes them.
But when I load pdb symbols, exports somehow get (partially) wiped. They are not shown in the CPU and Symbols windows but the expression window does recognize them.

Let's take "kernel32.ExitProcess":
It doesn't show up in the CPU and Symbols windows, but entering "ExitProcess" in the expression window tells me: "Correct expression! -> kernel32.772379D8", although it should tell me: "Correct expression! -> kernel32.ExitProcess". And when i go to that location in the CPU window, the address just says "772379D8" instead of "kernel32.ExitProcess".

I'm not sure, why I'm not getting undecorated symbol names, but I think the problem with exports not being recognized correctly when loading pdb symbols has something to do with the fact that exports are actually treated as "labels" (as far as I can tell) and imports/symbols are treated as "symbols".

I'm using the newest release on a Win7 x64 machine. I'm running the 32 bit version as admin on a 32 bit target.

Other debuggers/disassemblers like Immunity or IDA Pro show correct symbol/export information, so I don't think it's me just being stupid.

I could probably provide some screenshots if necessary.

**Comment by mrexodia** [comment]
For me the symbols server has been super unstable and weird, see https://social.msdn.microsoft.com/Forums/en-US/35a31403-24f5-4552-8e3c-4c65f2b98c17/microsoft-symbol-server-is-slowbroken?forum=windbg perhaps there will be a statement there.

As for exports, x64dbg *does not* parse them in any way, it relies on dbghelp for the names of exports. If exports have symbols it will use that name instead of the export name. You can still access the export by using "module:ExportName" as x64dbg will try `GetProcAddress` on that module.

I have noticed issues with undecorated symbols, but it appears that private symbols [do not have the decorated form stored](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681366(v=vs.85).aspx):

> All symbols are presented in undecorated form.

> This option has no effect on global or local symbols because they are stored undecorated. This option applies only to public symbols.

Symbols are indeed treated as labels (and should be), you can find the exact code [here](https://github.com/x64dbg/x64dbg/blob/development/src/dbg/_exports.cpp#L119), maybe you can see an error with dbghelp somewhere, the documentation for that is very poor.

Now, there has been a change related to security with the symbol options. *Per default*, x64dbg does not allow dbghelp to read the debug information of the program, since the symbol path can go to a network share which dbghelp will happily attempt to load from without warning or option to disable. You can try calling `SymSetOptions(SymGetOptions() & ~SYMOPT_IGNORE_CVREC)` from a plugin to see if it makes any difference.

**Comment by webro666** [comment]
Since I've always worked with msdia instead of dbghelp, I just ran some tests and observed the following with dbghelp (at least on my system):

calling SymSetOptions without SYMOPT_UNDNAME will make undecorated names unavailable, no matter what. UnDecorateSymbolName will not give you any undecorated names.
calling SymSetOptions with SYMOPT_UNDNAME will undecorate all names automatically (decorated names will be lost). No need to call UnDecorateSymbolName in this case.
MSDN also states: "To use undecorated symbols, call the SymSetOptions function with the SYMOPT_UNDNAME option."

So, whatever is going on here, UnDecorateSymbolName is completely useless. If you specify SYMOPT_UNDNAME, you get undecorated symbols by default (meaning, you don't have to call it to get the undecorated name), if you don't specify SYMOPT_UNDNAME it will simply do nothing.

And about the exports problem, I observed the following:
If you let dbghelp find the corresponding .pdb file, it will just read symbols out of the pdb file and totally ignore the export table in the corresponding module. So if the .pdb file does not have export table symbols, you won't get any export table symbols.
If you don't let dbghelp find the .pdb file, it will read imports and exports from the module.

So, to fix undecorated symbols, you would probably have to specify SYMOPT_UNDNAME within SymSetOptions (if undecoration is set in engine options).

And to fix the exports problem, you would have to manually extract information from the export table in addition to getting symbols from dbghelp, if the .pdb does not store any export information.

I'm not sure, if I'm the only one with this strange behaviour..

**Comment by mrexodia** [comment]
The documentation of `SYMOPT_UNDNAME` can be seen as calling `UnDecorateSymbolName` on every symbol during the loading and serving those names to `SymFromAddr` and `SymEnum` you lose all information about decorated symbols which is generally not what you want and also why x64dbg doesn't use that option.

If I load x64dbg in x64dbg and load its symbols you see something like this:

![screenshot](https://i.imgur.com/ViFUQM3.png)

The 'decorated' symbol `<lambda_47baab08f63abb0acad11aadbc274841>::operator()` can be found plaintext in the PDB and is a private symbol (therefore there is no mangled name stored since external components don't have to see is and thus it doesn't need an external mangled name).

I do have quite a lot of cases that don't have an undecorated form, one example: `??_7?$TaskThread_@P6AXXZ$$$V@@6B@`

My guess is that the dbghelp version just doesn't support this, try updating it to the one shipped with the latest WinDbg:

```
undname ??_7?$TaskThread_@P6AXXZ$$$V@@6B@
Microsoft (R) C++ Name Undecorator
Copyright (C) Microsoft Corporation. All rights reserved.

Undecoration of :- "??_7?$TaskThread_@P6AXXZ$$$V@@6B@"
is :- "const TaskThread_<void (__cdecl*)(void)>::`vftable'"
```

**Comment by mrexodia** [comment]
I did some more experimentation, turns out that `undname` uses `__unDNameEx`, which is also used by `UnDecorateSymbolName` and if I manually call `__unDNameEx` I don't get the same results are `undname`. Gotta love undocumented shit!

**Comment by webro666** [comment]
I've also done some more experimenting. I downloaded the latest debugging tools, copied all related files to the x64dbg directory where the exe resides, but I can't get undecorating to work. Public symbols in the form of _SymbolName@XX will not get undecorated without specifying SYMOPT_UNDNAME, no matter what params I specify in UnDecorateSymbolName. But that's not too big of a deal, because I will just go ahead and specify SYMOPT_UNDNAME and take the loss of decorated names.
But the fact, that exported api functions are not displayed in the CPU and Symbols windows is really kind of annoying.

So I tried to get a quick "hacky" workaround going like this:
In symbolinfo.cpp add the line
`
SymEnumExports(Base, EnumCallback, UserData);
`
to the end of the SymEnum function.

SymEnumExports looks like this (as I said, just a quick "hacky" version):
`
void SymEnumExports(duint Base, CBSYMBOLENUM EnumCallback, void* UserData)
`
`
{
`
`
	SYMBOLINFO symbol;
`
`
	memset(&symbol, 0, sizeof(SYMBOLINFO));
`
`
	symbol.isImported = false;
`
`
	apienumexports(Base, [&](duint base, const char *mod, const char* name, duint addr)
`
`
	{
`
`
		symbol.addr = addr;
`
`
		symbol.decoratedSymbol = (char *)name;
`
`
		symbol.undecoratedSymbol = (char *)name;
`
`
		EnumCallback(&symbol, UserData);
`
`
	});
`
`
}
`
It now shows exported functions in the Symbols window, but the CPU window still doesn't recognize exports :(

**Comment by mrexodia** [comment]
No, like I mentioned, x64dbg uses SymFromAddr and does not (yet parse
export tables from the file). You could call apienumexports and set labels
for all of them...

It js really strange that SYM_UNDNAME undecorates the symbols correctly and
the manual undecoration function doesn't...

**Comment by webro666** [comment]
Yes, pretty annoying that ms stuff sometimes doesn't work as intended :(
