### ISSUE TITLE
Breakpoint UD2

### ISSUE THREAD

**Issue by giordano-lanzola** [x64dbg/x64dbg#1190]
First,, thanks for this magnificent tool ! Apologies for this message but could not find any other board on the net.

I'm debugging a WinService and looks like I must use BP type UD2 since INT3 locks each time the system. However each BP seems to only works once. After triggering the first stop in control execution, a BP will not cause any other break unless it is manually disabled and re-enabled again. Sometimes even the hit count reported on the Breakpoint panel is lower (by 1) than the number displayed in the BP edit widget.

**Comment by mrexodia** [comment]
I didn't actually ever test UD2 breakpoints. The implementation looks correct but since your use case is very specific you should probably insert some printfs in TitanEngine and see what behavior is actually observed in your case. Alternatively provide a simple, easy to reproduce example and someone will probably take a look at it.

**Comment by giordano-lanzola** [comment]
Dear Mr.Exodia,

thanks a lot for your kind reply. I tried to reproduce the example using a
simple test *.exe application with no luck, since everything worked fine in
that case, However, please consider that I'm not really in this stuff and
I'm just debugging an application to understand its logic.

I can only add some more details, in case you are interested:
-) the debuggee is a Win32 Service and I have to attach the x32dbg to the
running instance every time. -) x32dbg is launched with Administrator
privileges;
-) I'm just placing breakpoints in the app module (not in system *.dll);
-) when using INT3 or Long INT3 the x32dbg debugger freezes on the first
breakpoint hit. It seems to work only when setting Breakpoint type to UD2;
-) when execution is resumed after hitting a breakpoint, hitting the same
breakpoint again will not cause the execution to break anymore (unless I
manually disable and reenable the breakpoint each time);
-) I'm testing the same with OllyDB (that has a very ugly interface and
fewer features compared to yours) and everything seems to work fine out of
the box. That is the breakpoints correctly stop execution upon every
invocation.

I would be very glad to send you (privately) the software that is causing
the problem, but it is meant to work with a proprietary monitoring device
connected through USB (as a HID class). In fact my debugging involves
(trying) to make some sense out of the data that is sent over the HID
report data, and captured with Wireshark, to (hope-fully/lessly) port it to
Android.

Best Regards

--
giordano

**Comment by mrexodia** [comment]
I have just tried using UD2 breakpoints in a regular environment but they appear to be working correctly in that case...

**Comment by nmikhailov** [comment]
@mrexodia 

I have a very similar problem.

I debug third party usb userspace driver, which gets loaded in WUDHost.
If I set a INT3 BP, it will get hit only once, and x64dbg will print "Breakpoint reached not in list!" in logs.
When it breaks it displays RIP=address+1, so that probably why it can't find it. 
I tried to change default break type to UD2, it fixes "Breakpoint reached not in list!" but it still breaks only once.

My setup:
Win10 64bit in VirtualBox
I debug fingerprint reader usb userspace driver - https://download.lenovo.com/pccbbs/mobiles/l68b89a0.exe
(probably not needed)

I start x64db, attach to WUDFHost.exe(i think there should have be one instance per winusb.sys USB device), it has synaWudfBioUsb.dll loaded which I am intrested in.
When I set a UD2 BP anywhere(for example in CryptDecrypt in advapi32.dll), it will get hit only once.

As you can see, my setup is hardware-dependent so you can try just attaching to WUDFHost.exe and setting breakpoint somewhere there.

**Comment by nmikhailov** [comment]
I have minimized setup:

1. Attach to SearchIndexer.exe
2. Add BP on msvcrt.dll.malloc
3. It should call malloc each time you try to find something in Explorer, but it will only trigger once. If you will disable/enable it, it will start working.

**Comment by nmikhailov** [comment]
I have found that the problem is in the Titan Engine, and how it handles debug permissions.
I have created PR for it: https://bitbucket.org/titanengineupdate/titanengine-update/pull-requests/11/disable-dropping-of-debug-privileges/diff

**Comment by RedFox0313** [comment]
I don't know if it has been fixed, but the problem still occurs, for example, in StreamFab, and specifically in libcef.dll, when you choose to download or simply load the page, it stops at UD2, and no matter what you do, step, run, etc., it crashes and closes.

**Comment by RedFox0313** [comment]
I don't know if it has been fixed, but the problem still occurs, for example, in StreamFab, and specifically in libcef.dll, when you choose to download or simply load the page, it stops at UD2(0F0B), and no matter what you do, step, run, etc., it crashes and closes.

**Comment by mrexodia** [comment]
That is most likely because of `NtSetInformationThread` with `ThreadHideFromDebugger`

**Comment by RedFox0313** [comment]
Thank you for the quick reply, and is there any solution without compiling the code? Maybe some additional option in x64dbg will be possible in newer versions? I also noticed a bug when you find some pattern in references and add brakepoints and then disable them, all brakepoints disappear, and sometimes after restoring the brake point x64dbg crashes, sometimes I also can't find the right patterns
![2024-11-05_162728](https://github.com/user-attachments/assets/9eb7bbf4-74bb-4294-b62f-2179a9f4bdf1)
