### ISSUE TITLE
disassembly view incorrectly restores page protection in certain cases which can reveal presence of debugger

### ISSUE THREAD

**Issue by changeofpace** [x64dbg/x64dbg#1374]
Viewing page boundaries in the CPU tab can alter page protection.  When this happens, the affected memory region seems to be combined with the preceding memory region.  This repo exploits this bug to detect the presence of x64dbg: https://github.com/changeofpace/x64dbg-Anti-Debug-POC

before viewing the boundary:

![before](https://cloud.githubusercontent.com/assets/18407097/21232605/2d9ff096-c2ba-11e6-8e68-99cdbaa044c9.png)

after:

![after](https://cloud.githubusercontent.com/assets/18407097/21232608/30726b14-c2ba-11e6-8f4e-33e9f6bfee13.png)

I would guess that when the CPU view is being generated or updated, any page protection check occurs after the disassembler accesses the noaccess page.  In this image the last disassembled instruction in the view crosses the noaccess page boundary:

![disassembly1](https://cloud.githubusercontent.com/assets/18407097/21233161/2d22dd16-c2bc-11e6-93a1-47b96cf68fcf.png)

![disassembly2](https://cloud.githubusercontent.com/assets/18407097/21233166/2feb07a8-c2bc-11e6-98e7-3c92d06feaa3.png)

**Comment by mrexodia** [comment]
This is half-expected behavior. If x64dbg cannot read a memory page it will change the protection to `PAGE_EXECUTE_READWRITE` to read the page anyway. Probably a good solution is to only allow this change in page protection if the debuggee is not running.

What seems strange is that the pages somehow get merged (meaning that x64dbg incorrectly restores the page protection) I will that that out further...

**Comment by changeofpace** [comment]
I forgot to add that this was designed for x64 and tested on Windows 7 x64 Professional.  Not sure how it behaves on x32.  I'll update when I get around to testing it.
