### ISSUE TITLE
if opcode have jmp "register" : g and ctrl+a command will be error 

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1409]
like jmp rax/rcx/rdx/rxx.....

![gif](https://cloud.githubusercontent.com/assets/16742566/21637065/3a439050-d2a0-11e6-888c-d9f0975f498b.gif)

png：
![1](https://cloud.githubusercontent.com/assets/16742566/21637309/5f05d21c-d2a1-11e6-9ab8-55955455c455.png)

**Comment by torusrxxx** [comment]
间接转移指令现在不支持在流程图中跟踪，因为有很多虚拟机都在用这种指令，它指向的代码无法确定。不过，可以编写或者找到一个根据特定壳进行编写的插件来实现这个功能。Indirect
control transfer instruction is not supported in graph, because obfuscated
code are using fake indirect jumps pointing to garbage, and the code it
points to is not certain. However, a plugin can be made or found to
implement it based on the protection.
