### ISSUE TITLE
The ASM file is not refreshed in the Source View tab

### ISSUE THREAD

**Issue by dfrunza** [x64dbg/x64dbg#1443]
The program being debugged has been build with MASM. After applying a modification to the source ASM file, and rebuilding the program, the dissassembly is refreshed, but the source file is not.

**Comment by mrexodia** [comment]
Just close the relevant source tab. Also know that you cannot update the
source code while debugging an application.

**Comment by dfrunza** [comment]
I did close and re-opened the source tab - does not help (actually it's worse - the view does not load at all, not even the old source, the window is just blank).
The workflow is : stop the debugging (Alt+F2); modify source code; rebuild the app with debug symbols; start debugging (Ctrl+F2). The disassembly view is updated with the fresh executable, and the expectation is that the source code view should be updated too.

**Comment by mrexodia** [comment]
@dfrunza The expected behavior now is that the source files are closed on debuggee termination. You need to enable 'source code debugging' to automatically open the source for the current EIP/RIP. Per default there is no interaction with source code because it's awfully slow so it will not be reloaded.
