### ISSUE TITLE
Operating system is not supported 

### ISSUE THREAD

**Issue by Hypophrenia** [x64dbg/x64dbg#1548]
I've update my operating system to win10 1703 , and everything is fine.
but when I updated the x64dbg to the newest version. 
everytime I click the plugin Scylla , it give me a warning ::
![capture](https://cloud.githubusercontent.com/assets/13413791/25129044/f1b885fe-246e-11e7-84fd-83fe1e193dde.PNG)

**operating system is not supported Continue anyway?**

**Comment by mrexodia** [comment]
If you press ok, will scylla work as expected?

**Comment by mrexodia** [comment]
Okay so the reason is that Scylla doesn't expect newer versions of Windows when checking for the OS version. This is exposed just now because of #1490 which turns on support for newer versions of Windows. It can be fixed in Scylla quite easily which I'm doing right now but I leave this information here just in case.

**Comment by mrexodia** [comment]
@Hypophrenia until the next release comes out you can use https://mega.nz/#!HlJznDJZ!Lzn6C2GhL-IU52Vtlvjuz7wMB8ogQCSzvkwJPIM8nHQ

**Comment by Hypophrenia** [comment]
@mrexodia  it work as expected if I press ok , 

thanks.
