### ISSUE TITLE
Game crashes on breakpoint hit - New debugger suggestion

### ISSUE THREAD

**Issue by MerovingianByte** [x64dbg/x64dbg#1671]
Games like Skyrim crashes when using x32dbg breakpoints. When the breakpoint hits, the game crashes. This doesn't happen for every breakpoint probably, but it happens very often.
An example on Skyrim is on this instruction: "0047F89F | sub al,4C". This instruction executes when any item gets subtracted from your inventory, either by consuming it or dropping it on the ground. If you toggle a breakpoint on this instruction, it will crash the game when it hits.

There is another popular hacking tool called Cheat Engine, it has 2 other debugger options called "VEH Debugger" and "Kernelmode Debugger". If any of these 2 debugger is used instead of the "Windows debugger", the game will not crash.

Maybe x32dbg could implement these debuggers as well? I'd really rather use x32dbg than cheat engine, but that is not possible for the moment unfortunately because of the issue described.

**Comment by wk-952** [comment]
`Cheat Engine` uses `Hardware` breakpoints by default,
![1](https://user-images.githubusercontent.com/11916365/28755800-c21f8564-7562-11e7-9418-2c44503cf9fc.png)

While `x64dbg` uses `INT3` breakpoints by default,
to use `Hardware` breakpoints right click on the instruction -> `Breakpoint` -> `Set Hardware on Execution`
![2](https://user-images.githubusercontent.com/11916365/28755835-3ee1a2c6-7563-11e7-938e-3bab1a08048d.png)

**Comment by MerovingianByte** [comment]
That's not the problem. The game will crash if using hardware or software breakpoint on x32dbg. Cheat Engine also crashes if the windows debugger is used, it only works if it's used "VEH Debugger" or "Kernelmode Debugger"

**Comment by blaquee** [comment]
Sounds like theres some anti-debug being used by the game, in which case you'll need to identify what it is and possibly write a plugin to circumvent it. CE's VEH debugger utilizes Vectored Exception handlers as a replacement for conventional breakpoints, if that gets around the game my first guess would be to see if the game utilizes any thread based Strutured Exception handlers to see if you're using any debuggers (second pass to their SEH and if its a breakpoint exception would be a prime way to see).

Also did u try playing with the other breakpoint options in x32dbg? besides int3, there is long int3 and UD2.

**Comment by MerovingianByte** [comment]
Tried those options on x32dbg, crashes the game anyway.

**Comment by mrexodia** [comment]
I tested myself, I searched all strings for `SaveSettings`, but a breakpoint there and open/close the menu. The mouse disappeared but after I pressed F9 the game resumed normally...

**Comment by MerovingianByte** [comment]
I think it's because of Steam. The game must not have any protection natively, because I got a cracked version and the game didn't crash. I found this: http://www.thehackerwithin.com/blog/11-08-07/Steam_s_anti-debugging_code.aspx

Apparently VEH debugger gets around the protection.

**Comment by mrexodia** [comment]
Scyllahide should bypass this if you attach to the process on time. You can
also use TitanHide which disables it from the kernel.

**Comment by mrexodia** [comment]
There are no plans to implement a VEH debugger. It could (and has been) done but it's annoying to maintain.

**Comment by Jedi0n** [comment]
"annoying to maintain" LOL
Could have just said you were too lazy?

**Comment by mrexodia** [comment]
Could we just say you're banned from the issue tracker?

**Comment by Jedi0n** [comment]
Cause I can be quite a dick some times 😏 
From: Jedi0n <Jedi0n@protonmail.com>
Sent
10:17 AM (2 hours ago)
To: mr.exodia.tpodt@gmail.com
Truth hurts both ways doesn't it

To be honest, I am no better :)

Sorry if it offended you so deeply, but I am only only voice my friend.

Thank you for your work. You and the others have turned a great deal of effort into an efficient and stable build. It goes without saying that you should be respected for that alone.

I should have said that before criticizing and maybe my words would not have felt so harsh.

Either way. I hope you read this and does not fail onto deaf anti-spam bot ears.

caio


Sent with ProtonMail Secure Email.

From: Duncan Ogilvie <mr.exodia.tpodt@gmail.com>
11:49 AM (9 minutes ago)
To: Jedi0n
I pretty much spend every free hour of my life on this project so I don't like people calling me lazy or tell me I don't work hard because their issue is being ignored.

I'll remove your ban from the issue tracker, because that was impulsive and unnecessary. But I would appreciate it if you post this conversation there.

Also you can always take up maintaining a VEH debugger plugin, there is one available called xdbg by brock7.

Duncan
