### ISSUE TITLE
Can't find entry point

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1676]
build tools：
```
vs2015 up3 
qt 5.8
```
all project can compile successfully 

![qq 20170802210925](https://user-images.githubusercontent.com/16742566/28875160-1faee7d6-77c7-11e7-87b7-deb35431d434.png)

![qq 20170802211107](https://user-images.githubusercontent.com/16742566/28875162-230b7534-77c7-11e7-8e3a-21a61c6104eb.png)

**Comment by mrexodia** [comment]
VS2015 is **not** supported. See [here](https://github.com/x64dbg/x64dbg/wiki/Compiling-the-whole-project)

> **Notice**: It is important to install the **exact** versions of the tools mentioned hereafter (special exception for Visual Studio 2013, for which you can also use the Professional or Enterprise editions). Don't come complaining if you didn't install the correct versions of the tools.

**Comment by mrexodia** [comment]
Solution (probably): delete all Qt DLLs from x64dbg `bin` directory.

**Comment by Mattiwatti** [comment]
Since I'm a rebel I have always stubbornly ignored the advice in the wiki, and it has been possible to compile x64dbg with VS2015 for as long as I can remember, as well as with VS2017 and even Clang/C2 3.8 (with some fixes) when those came out. So I'm going to out on a limb and say your Qt binaries don't match the x64dbg binaries you have compiled.

If you lifted the Qt DLLs from the release distribution, this will never work because those DLLs are compiled with VS2013. You'll have to compile Qt from source (this is a nightmare by the way). If you did already compile Qt from source, my guess would be that an accidental mismatch still slipped in, it's possible with Qt's 10000 configuration options. At the very least your QMAKESPEC (= compiler) and Windows SDK version should match the ones you're using to compile x64dbg.
