### ISSUE TITLE
The debugger crashes on WINE

### ISSUE THREAD

**Issue by johnfound** [x64dbg/x64dbg#1740]
I tried to use x32dbg on Linux but it crashes. Here is the console output:
```
$wine ./x32dbg.exe 
wine: Call from 0x7b43c82c to unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z, aborting
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:dbghelp:fetch_thread_info Couldn't open thread 102 (87)
wine: Unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z called at address 0x2e50023:0x7b43c82c (thread 005a), starting debugger...
Unhandled exception: unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z called in 32-bit code (0x7b43c82c).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b43c82c ESP:0033eda4 EBP:0033ee28 EFLAGS:00000212(   - --  I   -A- - )
 EAX:7b429159 EBX:00000004 ECX:0033edd0 EDX:0033ee4c
 ESI:7e799000 EDI:02e5d638
Stack dump:
0x0033eda4:  00000000 0033edb8 7bc52091 0033edd0
0x0033edb4:  7b63a000 0033eec8 80000100 00000001
0x0033edc4:  00000000 7b43c82c 00000002 7e799000
0x0033edd4:  7e799664 00000000 00000000 00000000
0x0033ede4:  4d430001 02e5d618 00000170 00000000
0x0033edf4:  00000000 00000000 7b485ad0 00520000
Backtrace:
=>0 0x7b43c82c RaiseException+0x9c(code=<couldn't compute location>, flags=<couldn't compute location>, nbargs=<couldn't compute location>, args=<couldn't compute location>) [/work/cwork/WineGit/wine/dlls/kernel32/except.c:85] in kernel32 (0x0033ee28)
  1 0x7e798cd7 __wine_spec_unimplemented_stub+0x36(module="msvcp120.dll", function="??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z") [/work/cwork/WineGit/wine/dlls/winecrt0/stub.c:34] in msvcp120 (0x0033ee60)
  2 0x7e739405 __wine_stub_msvcp120_dll_92+0x28() in msvcp120 (0x0033ee98)
  3 0x00bf71db in x32dbg (+0x671da) (0x0033ee98)
  4 0x00bf7384 in x32dbg (+0x67383) (0x0033eebc)
  5 0x00bf726f in x32dbg (+0x6726e) (0x0033eee0)
  6 0x00bf73fe in x32dbg (+0x673fd) (0x0033ef00)
  7 0x00bf8498 in x32dbg (+0x68497) (0x0033ef20)
  8 0x00c2279b in x32dbg (+0x9279a) (0x0033fd0c)
  9 0x00637182 in x32gui (+0x7181) (0x0053cb58)
  10 0x005200a8 (0x008556d8)
  11 0x006362c0 in x32gui (+0x62bf) (0x00634ab0)
  12 0x85388415 (0xfff18b56)
0x7b43c82c RaiseException+0x9c [/work/cwork/WineGit/wine/dlls/kernel32/except.c:85] in kernel32: addl	$12,%esp
85	}
Modules:
Module	Address			Debug info	Name (132 modules)
PE	  340000-  35a000	Deferred        lz4
PE	  360000-  384000	Deferred        jansson
PE	  390000-  3a1000	Deferred        devicenameresolver
PE	  400000-  410000	Deferred        x32dbg
PE	  630000-  995000	Export          x32gui
PE	  9a0000-  b8f000	Deferred        snowman
PE	  b90000-  c88000	Export          x32dbg
PE	  c90000- 1141000	Deferred        keystone
PE	 1150000- 12dc000	Deferred        capstone
PE	 12e0000- 14a8000	Deferred        yara
PE	 14b0000- 162b000	Deferred        xedparse
PE	 1630000- 16ee000	Deferred        titanengine
PE	 16f0000- 1bbe000	Deferred        qt5gui
PE	 2220000- 231d000	Deferred        qwindows
PE	10000000-10010000	Deferred        x32bridge
PE	61c40000-61c52000	Deferred        ldconvert
PE	64000000-640d6000	Deferred        qt5network
PE	65000000-65447000	Deferred        qt5widgets
PE	67000000-6747a000	Deferred        qt5core
ELF	7b400000-7b7ea000	Dwarf           kernel32<elf>
  \-PE	7b410000-7b7ea000	\               kernel32
ELF	7bc00000-7bcfb000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcfb000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7ca9e000-7caba000	Deferred        libgcc_s.so.1
ELF	7cd9f000-7cdbe000	Deferred        wintab32<elf>
  \-PE	7cda0000-7cdbe000	\               wintab32
ELF	7ce8f000-7cfc2000	Deferred        oleaut32<elf>
  \-PE	7ceb0000-7cfc2000	\               oleaut32
ELF	7cfc2000-7cfc9000	Deferred        libxfixes.so.3
ELF	7cfc9000-7cfd4000	Deferred        libxcursor.so.1
ELF	7cfd4000-7cfe7000	Deferred        libxi.so.6
ELF	7cfe7000-7cfeb000	Deferred        libxcomposite.so.1
ELF	7cfeb000-7cff8000	Deferred        libxrandr.so.2
ELF	7cff8000-7d004000	Deferred        libxrender.so.1
ELF	7d004000-7d00b000	Deferred        libxxf86vm.so.1
ELF	7d10b000-7d136000	Deferred        libxcb.so.1
ELF	7d136000-7d283000	Deferred        libx11.so.6
ELF	7d283000-7d298000	Deferred        libxext.so.6
ELF	7d2a0000-7d2d8000	Deferred        uxtheme<elf>
  \-PE	7d2b0000-7d2d8000	\               uxtheme
ELF	7d2d8000-7d364000	Deferred        winex11<elf>
  \-PE	7d2e0000-7d364000	\               winex11
ELF	7d364000-7d38e000	Deferred        iphlpapi<elf>
  \-PE	7d370000-7d38e000	\               iphlpapi
ELF	7d38e000-7d3be000	Deferred        netapi32<elf>
  \-PE	7d390000-7d3be000	\               netapi32
ELF	7d3be000-7d3c2000	Deferred        libxinerama.so.1
PE	7d3c2000-7d3d6000	Deferred        api-ms-win-core-localization-l1-
PE	7d3d0000-7d3d6000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	7d3d6000-7d3ea000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	7d3e0000-7d3ea000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	7d3ea000-7d3fe000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	7d3f0000-7d3fe000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	7d3fe000-7d4bf000	Deferred        msvcrt<elf>
  \-PE	7d420000-7d4bf000	\               msvcrt
ELF	7d4bf000-7d5dc000	Deferred        comctl32<elf>
  \-PE	7d4d0000-7d5dc000	\               comctl32
ELF	7d5dc000-7d6c7000	Deferred        comdlg32<elf>
  \-PE	7d5e0000-7d6c7000	\               comdlg32
ELF	7d6c7000-7d795000	Deferred        crypt32<elf>
  \-PE	7d6d0000-7d795000	\               crypt32
ELF	7d7da000-7d7e1000	Deferred        libxdmcp.so.6
ELF	7d7e1000-7d7e6000	Deferred        libxau.so.6
ELF	7d7e6000-7d7fe000	Deferred        libresolv.so.2
ELF	7d7fe000-7d81e000	Deferred        dnsapi<elf>
  \-PE	7d800000-7d81e000	\               dnsapi
ELF	7d81e000-7d846000	Deferred        mpr<elf>
  \-PE	7d820000-7d846000	\               mpr
ELF	7d846000-7d884000	Deferred        winspool<elf>
  \-PE	7d850000-7d884000	\               winspool
ELF	7d884000-7d89e000	Deferred        imagehlp<elf>
  \-PE	7d890000-7d89e000	\               imagehlp
ELF	7d89e000-7d8d9000	Deferred        ws2_32<elf>
  \-PE	7d8b0000-7d8d9000	\               ws2_32
ELF	7d8d9000-7d950000	Deferred        shlwapi<elf>
  \-PE	7d8f0000-7d950000	\               shlwapi
ELF	7d950000-7db9c000	Deferred        shell32<elf>
  \-PE	7d960000-7db9c000	\               shell32
ELF	7db9c000-7dbc7000	Deferred        msacm32<elf>
  \-PE	7dba0000-7dbc7000	\               msacm32
ELF	7dbc7000-7dc49000	Deferred        rpcrt4<elf>
  \-PE	7dbd0000-7dc49000	\               rpcrt4
ELF	7dc49000-7dda3000	Deferred        ole32<elf>
  \-PE	7dc60000-7dda3000	\               ole32
ELF	7dda3000-7de5c000	Deferred        winmm<elf>
  \-PE	7ddb0000-7de5c000	\               winmm
ELF	7de5c000-7dec3000	Deferred        dbghelp<elf>
  \-PE	7de60000-7dec3000	\               dbghelp
ELF	7dec3000-7dee7000	Deferred        imm32<elf>
  \-PE	7ded0000-7dee7000	\               imm32
ELF	7e0ad000-7e0df000	Deferred        libexpat.so.1
ELF	7e0df000-7e12a000	Deferred        libfontconfig.so.1
ELF	7e12a000-7e1a2000	Deferred        libpcre.so.1
ELF	7e1a2000-7e2ce000	Deferred        libglib-2.0.so.0
ELF	7e2ce000-7e369000	Deferred        libharfbuzz.so.0
ELF	7e369000-7e3a6000	Deferred        libpng16.so.16
ELF	7e3a6000-7e473000	Deferred        libfreetype.so.6
ELF	7e474000-7e488000	Deferred        psapi<elf>
  \-PE	7e480000-7e488000	\               psapi
ELF	7e4b3000-7e558000	Deferred        krnl386.exe16.so
PE	7e4c0000-7e558000	Deferred        krnl386.exe16
ELF	7e558000-7e5c5000	Deferred        libncursesw.so.6
ELF	7e5d7000-7e5f0000	Deferred        libz.so.1
ELF	7e5f0000-7e605000	Deferred        comm.drv16.so
PE	7e600000-7e605000	Deferred        comm.drv16
ELF	7e605000-7e6f2000	Deferred        msvcr120<elf>
  \-PE	7e620000-7e6f2000	\               msvcr120
ELF	7e6f2000-7e810000	Dwarf           msvcp120<elf>
  \-PE	7e730000-7e810000	\               msvcp120
ELF	7e810000-7e887000	Deferred        advapi32<elf>
  \-PE	7e820000-7e887000	\               advapi32
ELF	7e887000-7e9b5000	Deferred        gdi32<elf>
  \-PE	7e890000-7e9b5000	\               gdi32
ELF	7e9b5000-7eb8e000	Deferred        user32<elf>
  \-PE	7e9d0000-7eb8e000	\               user32
ELF	7eec0000-7eed3000	Deferred        libnss_files.so.2
ELF	7eed3000-7eee1000	Deferred        libnss_nis.so.2
ELF	7eee1000-7eefc000	Deferred        libnsl.so.1
ELF	7eefc000-7efc0000	Deferred        libm.so.6
ELF	7efc0000-7efd1000	Deferred        libbz2.so.1.0
ELF	7efd1000-7efe6000	Deferred        system.drv16.so
PE	7efe0000-7efe6000	Deferred        system.drv16
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7387000-f738c000	Deferred        libdl.so.2
ELF	f738c000-f7562000	Deferred        libc.so.6
ELF	f7562000-f7581000	Deferred        libpthread.so.0
ELF	f7586000-f7590000	Deferred        libnss_compat.so.2
ELF	f75c1000-f7777000	Dwarf           libwine.so.1
ELF	f7779000-f77a0000	Deferred        ld-linux.so.2
ELF	f77a2000-f77a3000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000025    0
	00000022    0
	0000001d    0
	00000018    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000028    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	0000001f    0
	0000001e    0
	0000001c    0
00000020 winedevice.exe
	00000029    0
	00000024    0
	00000023    0
	00000021    0
00000059 (D) Z:\work\Install\Programming\debuggers\x64dbg\snapshot_2017-09-12_00-45\release\x32\x32dbg.exe
	00000065    0
	00000064    0
	00000063    0
	00000062    0
	00000061    0
	00000060    0
	0000005a    0 <==
0000005b explorer.exe
	0000005f    0
	0000005e    0
	0000005d    0
	0000005c    0
System information:
    Wine build: wine-2.16-53-gc9f72ccec2
    Platform: i386
    Version: Windows 98
    Host system: Linux
    Host version: 4.9.51-1-MANJARO
```

**Comment by mrexodia** [comment]
Wine is not supported, but I created a branch that should make it work fine https://github.com/x64dbg/x64dbg/commit/16d89ee6983fdaae014660830c6b20af787bdcac

**Comment by ezxpro** [comment]
I know Wine is not supported but I thought it might be useful to report that this issue is back on the latest release (snapshot_2017-11-30_20-27)
When I try to run x32dbg I get 
`vlash@vl-arch ~/Downloads/release/x32 % wine x32dbg.exe 
fixme:file:FindFirstFileExW flags not implemented 0x00000002
Adjust scroll bars for new size
fixme:file:FindFirstFileExW flags not implemented 0x00000002
wine: Call from 0x7b43d53c to unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z, aborting
fixme:dbghelp:elf_search_auxv can't find symbol in module
fixme:dbghelp:fetch_thread_info Couldn't open thread 70 (87)
wine: Unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z called at address 0x7bca0023:0x7b43d53c (thread 003f), starting debugger...
Unhandled exception: unimplemented function msvcp120.dll.??0_Concurrent_queue_base_v4@details@Concurrency@@IAE@I@Z called in 32-bit code (0x7b43d53c).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b43d53c ESP:0032eda4 EBP:0032ee28 EFLAGS:00200212(   - --  I   -A- - )
 EAX:7b429d1d EBX:00000004 ECX:0032edd0 EDX:0032ee4c
 ESI:7eaccb20 EDI:02ae9200
Stack dump:
0x0032eda4:  00000000 0032edb8 7bc76961 0032edd0
0x0032edb4:  7b63d000 0032eec8 80000100 00000001
0x0032edc4:  00000000 7b43d53c 00000002 7eaccb20
0x0032edd4:  7eacd184 00211558 02ae8678 7ea16000
0x0032ede4:  00c374a8 7b63d000 00211558 c0000047
0x0032edf4:  7bcaf7b6 0032ef10 7b488410 00410000
Backtrace:
=>0 0x7b43d53c in kernel32 (+0x1d53c) (0x0032ee28)
  1 0x7eacc6d7 in msvcp120 (+0x6c6d6) (0x0032ee60)
  2 0x7ea6c7a5 in msvcp120 (+0xc7a4) (0x0032ee98)
  3 0x00b690db in x32dbg (+0x690da) (0x0032ee98)
  4 0x00b69284 in x32dbg (+0x69283) (0x0032eebc)
  5 0x00b6916f in x32dbg (+0x6916e) (0x0032eee0)
  6 0x00b692fe in x32dbg (+0x692fd) (0x0032ef00)
  7 0x00b6a398 in x32dbg (+0x6a397) (0x0032ef20)
  8 0x00b94f6b in x32dbg (+0x94f6a) (0x0032fd0c)
  9 0x005274b7 in x32gui (+0x74b6) (0x00424308)
  10 0x004100d0 (0x0077c878)
  11 0x005265f0 in x32gui (+0x65ef) (0x00524de0)
0x7b43d53c: addl	$12,%esp
Modules:
Module	Address			Debug info	Name (138 modules)
PE	  330000-  34a000	Deferred        lz4
PE	  350000-  374000	Deferred        jansson
PE	  380000-  391000	Deferred        devicenameresolver
PE	  400000-  410000	Deferred        x32dbg
PE	  520000-  910000	Export          x32gui
PE	  910000-  aff000	Deferred        snowman
PE	  b00000-  c4a000	Export          x32dbg
PE	  c50000- 1101000	Deferred        keystone
PE	 1110000- 129c000	Deferred        capstone
PE	 12a0000- 1468000	Deferred        yara
PE	 1470000- 15eb000	Deferred        xedparse
PE	 15f0000- 16ae000	Deferred        titanengine
PE	 16b0000- 1b7e000	Deferred        qt5gui
PE	 20d0000- 21cd000	Deferred        qwindows
PE	10000000-10011000	Deferred        x32bridge
PE	61c40000-61c52000	Deferred        ldconvert
PE	64000000-640d6000	Deferred        qt5network
PE	65000000-65447000	Deferred        qt5widgets
PE	67000000-6747a000	Deferred        qt5core
ELF	7b400000-7b7ee000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b7ee000	\               kernel32
ELF	7bc00000-7bd2d000	Deferred        ntdll<elf>
  \-PE	7bc40000-7bd2d000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7e88e000-7e8fc000	Deferred        libncursesw.so.6
ELF	7e915000-7e939000	Deferred        imm32<elf>
  \-PE	7e920000-7e939000	\               imm32
ELF	7e939000-7ea27000	Deferred        msvcr120<elf>
  \-PE	7e960000-7ea27000	\               msvcr120
ELF	7ea27000-7eb45000	Dwarf           msvcp120<elf>
  \-PE	7ea60000-7eb45000	\               msvcp120
ELF	7eb45000-7ebbf000	Deferred        advapi32<elf>
  \-PE	7eb50000-7ebbf000	\               advapi32
ELF	7ebbf000-7eced000	Deferred        gdi32<elf>
  \-PE	7ebd0000-7eced000	\               gdi32
ELF	7eced000-7eed1000	Deferred        user32<elf>
  \-PE	7ed00000-7eed1000	\               user32
ELF	7eed1000-7eee5000	Deferred        libnss_files.so.2
ELF	7eee5000-7ef00000	Deferred        libnsl.so.1
ELF	7ef00000-7efc4000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f5d17000-f5d33000	Deferred        libgcc_s.so.1
ELF	f6026000-f6045000	Deferred        wintab32<elf>
  \-PE	f6030000-f6045000	\               wintab32
ELF	f6067000-f619b000	Deferred        oleaut32<elf>
  \-PE	f6080000-f619b000	\               oleaut32
ELF	f619b000-f61cd000	Deferred        libcrypt.so.1
ELF	f61cd000-f625b000	Deferred        libcups.so.2
ELF	f6298000-f62a1000	Deferred        libffi.so.6
ELF	f62a1000-f632b000	Deferred        libgmp.so.10
ELF	f632b000-f6361000	Deferred        libhogweed.so.4
ELF	f6361000-f639f000	Deferred        libnettle.so.6
ELF	f639f000-f63b4000	Deferred        libtasn1.so.6
ELF	f63b4000-f63e8000	Deferred        libidn.so.11
ELF	f63e8000-f652a000	Deferred        libp11-kit.so.0
ELF	f652a000-f66f2000	Deferred        libgnutls.so.30
PE	f66f3000-f6707000	Deferred        api-ms-win-core-localization-l1-
PE	f6700000-f6707000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	f6707000-f671b000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	f6710000-f671b000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	f671b000-f672f000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	f6720000-f672f000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	f672f000-f6736000	Deferred        libxfixes.so.3
ELF	f673b000-f6773000	Deferred        uxtheme<elf>
  \-PE	f6740000-f6773000	\               uxtheme
ELF	f68ea000-f691c000	Deferred        libexpat.so.1
ELF	f691c000-f6967000	Deferred        libfontconfig.so.1
ELF	f6967000-f69df000	Deferred        libpcre.so.1
ELF	f69df000-f6b11000	Deferred        libglib-2.0.so.0
ELF	f6b11000-f6bb6000	Deferred        libharfbuzz.so.0
ELF	f6bb6000-f6bf4000	Deferred        libpng16.so.16
ELF	f6bf4000-f6c05000	Deferred        libbz2.so.1.0
ELF	f6c05000-f6cd2000	Deferred        libfreetype.so.6
ELF	f6cd2000-f6ce5000	Deferred        libxi.so.6
ELF	f6ce5000-f6ce9000	Deferred        libxcomposite.so.1
ELF	f6ce9000-f6cf6000	Deferred        libxrandr.so.2
ELF	f6cf6000-f6d02000	Deferred        libxrender.so.1
ELF	f6d02000-f6d09000	Deferred        libxxf86vm.so.1
ELF	f6d09000-f6d10000	Deferred        libxdmcp.so.6
ELF	f6d10000-f6d15000	Deferred        libxau.so.6
ELF	f6d15000-f6d40000	Deferred        libxcb.so.1
ELF	f6d40000-f6e8d000	Deferred        libx11.so.6
ELF	f6e8d000-f6ea2000	Deferred        libxext.so.6
ELF	f6ea2000-f6f2f000	Deferred        winex11<elf>
  \-PE	f6eb0000-f6f2f000	\               winex11
ELF	f6f2f000-f6f5a000	Deferred        iphlpapi<elf>
  \-PE	f6f40000-f6f5a000	\               iphlpapi
ELF	f6f5a000-f6f8a000	Deferred        netapi32<elf>
  \-PE	f6f60000-f6f8a000	\               netapi32
ELF	f6f8a000-f6fa2000	Deferred        libresolv.so.2
ELF	f6fa5000-f6fb1000	Deferred        libxcursor.so.1
ELF	f6fdf000-f6fff000	Deferred        dnsapi<elf>
  \-PE	f6ff0000-f6fff000	\               dnsapi
ELF	f6fff000-f70c2000	Deferred        msvcrt<elf>
  \-PE	f7020000-f70c2000	\               msvcrt
ELF	f70c2000-f70ea000	Deferred        mpr<elf>
  \-PE	f70d0000-f70ea000	\               mpr
ELF	f70ea000-f716c000	Deferred        rpcrt4<elf>
  \-PE	f7100000-f716c000	\               rpcrt4
ELF	f716c000-f72c7000	Deferred        ole32<elf>
  \-PE	f7180000-f72c7000	\               ole32
ELF	f72c7000-f7306000	Deferred        winspool<elf>
  \-PE	f72d0000-f7306000	\               winspool
ELF	f7306000-f73f1000	Deferred        comdlg32<elf>
  \-PE	f7310000-f73f1000	\               comdlg32
ELF	f73f1000-f740c000	Deferred        imagehlp<elf>
  \-PE	f7400000-f740c000	\               imagehlp
ELF	f740c000-f742b000	Deferred        bcrypt<elf>
  \-PE	f7410000-f742b000	\               bcrypt
ELF	f742b000-f74fc000	Deferred        crypt32<elf>
  \-PE	f7430000-f74fc000	\               crypt32
ELF	f74fc000-f7538000	Deferred        ws2_32<elf>
  \-PE	f7500000-f7538000	\               ws2_32
ELF	f7538000-f7656000	Deferred        comctl32<elf>
  \-PE	f7540000-f7656000	\               comctl32
ELF	f7656000-f7671000	Deferred        aclui<elf>
  \-PE	f7660000-f7671000	\               aclui
ELF	f7671000-f76ea000	Deferred        shlwapi<elf>
  \-PE	f7680000-f76ea000	\               shlwapi
ELF	f76ea000-f79be000	Deferred        shell32<elf>
  \-PE	f7700000-f79be000	\               shell32
ELF	f79be000-f7a78000	Deferred        winmm<elf>
  \-PE	f79d0000-f7a78000	\               winmm
ELF	f7a78000-f7ae0000	Deferred        dbghelp<elf>
  \-PE	f7a80000-f7ae0000	\               dbghelp
ELF	f7ae0000-f7aee000	Deferred        libnss_nis.so.2
ELF	f7af0000-f7af5000	Deferred        libdl.so.2
ELF	f7af6000-f7b00000	Deferred        libnss_compat.so.2
ELF	f7b00000-f7b04000	Deferred        libxinerama.so.1
ELF	f7b04000-f7b18000	Deferred        psapi<elf>
  \-PE	f7b10000-f7b18000	\               psapi
ELF	f7b18000-f7b31000	Deferred        libz.so.1
ELF	f7b31000-f7d05000	Deferred        libc.so.6
ELF	f7d05000-f7d24000	Deferred        libpthread.so.0
ELF	f7d24000-f7ef5000	Dwarf           libwine.so.1
ELF	f7ef7000-f7f1e000	Deferred        ld-linux.so.2
ELF	f7f21000-f7f22000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) H:\Downloads\release\x32\x32dbg.exe
	[H:\Downloads\release\x32\x32dbg.exe]
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
	0000002e    0
	0000002d    0
	00000009    0 <==
0000000e services.exe
	00000024    0
	0000001f    0
	00000015    0
	00000012    0
	0000000f    0
00000010 explorer.exe
	0000002c    0
	0000002b    0
	0000002a    0
	00000011    0
00000013 winedevice.exe
	0000001c    0
	00000019    0
	00000018    0
	00000014    0
0000001d plugplay.exe
	00000021    0
	00000020    0
	0000001e    0
00000022 winedevice.exe
	00000029    0
	00000026    0
	00000025    0
	00000023    0
00000036 explorer.exe
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
System information:
    Wine build: wine-2.21 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.14.3-1-ARCH
`
Same happens with x64bdg, however, I won't post the error here unless you ask me, so the comment doesn't get too extensive.

**Comment by mrexodia** [comment]
Did you try the “wine” branch that removes the concurrency dependency?

**Comment by ezxpro** [comment]
No, I didn't even know such a branch existed. I'll try to download and test it.

**Comment by mrexodia** [comment]
Latest snapshot should be here in a few minutes: https://ci.appveyor.com/project/mrexodia/x64dbg/build/1.0.338/artifacts

**Comment by ezxpro** [comment]
Indeed I have to praise you for the quick response and I have to admit I've never seen anyone fix a bug so quickly. 

It seems to be working right now, I'll keep you up if any crashes pop up.

**Comment by ezxpro** [comment]
By the way, what has been changed to make it work again in wine?

**Comment by ezxpro** [comment]
Damn, how dumb I am. Only now I got that the "branch" you were talking about was x64dbg branch, but I thought it was a wine branch -.-

Anyways, thanks again haha
