### ISSUE TITLE
fix a problem with committing way too much memory

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#1777]
If `CreateFileMapping` is called with `INVALID_HANDLE_VALUE` it will commit gigabytes of memory. This (probably) happens [here](https://bitbucket.org/titanengineupdate/titanengine-update/src/e089f4af41a461b69017db3750f79fbaed1008df/TitanEngine/TitanEngine.Debugger.DebugLoop.cpp?at=master&fileviewer=file-view-default#TitanEngine.Debugger.DebugLoop.cpp-261) in TitanEngine.

It appears to fill up `hiberfil.sys` if you attach to chrome.exe

## CreateFileMapping MSDN

> If hFile is INVALID_HANDLE_VALUE, the calling process must also specify a size for the file mapping object in the dwMaximumSizeHigh and dwMaximumSizeLow parameters. In this scenario, CreateFileMapping creates a file mapping object of a specified size that is backed by the system paging file instead of by a file in the file system.

## GetFileSize MSDN

> If the function fails and lpFileSizeHigh is NULL, the return value is INVALID_FILE_SIZE. To get extended error information, call GetLastError. When lpFileSizeHigh is NULL, the results returned for large files are ambiguous, and you will not be able to determine the actual size of the file. It is recommended that you use GetFileSizeEx instead.

**Comment by Mattiwatti** [comment]
Re: `GetFileSize`: ideally `GetFileSizeEx` should always be used instead, but this function isn't available on XP. A more universal fix would be
```C++
IO_STATUS_BLOCK IoStatusBlock;
FILE_STANDARD_INFORMATION FileInfo;
NTSTATUS Status = NtQueryInformationFile(FileHandle, &IoStatusBlock, &FileInfo, sizeof(FileInfo), FileStandardInformation);
```
Anyway, above is a bit of a side track, since what the code is really doing is asking `NtCreateSection` for a `SEC_COMMIT` section that is backed by the pagefile, which is definitely not what you want since it concerns a specific DLL (file) load event. If `hFile` is `INVALID_HANDLE_VALUE`, `CreateFileMapping` should never be called and an error should be returned instead. `GetFileSize` being a terrible API might exacerbate the problem though because as MSDN says, it can return garbage values that would explain the high pagefile usage.

**Comment by mrexodia** [comment]
Doesn't the kernel refuse to load executables bigger than 4gb? Because that would make `GetFileSize` quite suitable...
