### ISSUE TITLE
fxrstor fxsave

### ISSUE THREAD

**Issue by UnlimitedChild** [x64dbg/x64dbg#1797]
5 Oct 2017 - Capstone disassembly
![image_3](https://user-images.githubusercontent.com/16466330/32414515-2882e9be-c229-11e7-9282-53566bc124b1.png)
11 Nov 2017 - Zyan Disassembler Engine
![image_2](https://user-images.githubusercontent.com/16466330/32414517-3a23ec54-c229-11e7-9deb-8912422e891e.png)

**Comment by mrexodia** [comment]
The bytes: `0F AE 05 20 A5 40 00`

**Comment by mrexodia** [comment]
ping @athre0z I think the issue is that the size 4096 is not recognized by the GUI, but I also don't see the 0x0040A520 anywhere is the operand data (apart from the text) so that could be a bug as well.

**Comment by athre0z** [comment]
Mh yeah, it is related to the size. The tokenizer doesn't support any sizes that don't have a string associated with them and it apparently works well with Capstone because, as it seems, it just wrongly reports `DWORD` size for such operands.

About the second thing: yep, I forgot to add `.value` in a few places in this func and it didn't error because it's a vararg formatting func.

I'll drop a PR later today.
