### ISSUE TITLE
Crash Bug - Plugin handling related

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#1818]
When having a plugin open for example Scylla (Ctrl+I).
Open up Scylla and then keep that open but close x64dbg itself
while keeping Scylla open. and it will crash.
Found the bug while coding a plugin with a form.
![crash](https://user-images.githubusercontent.com/1159592/32980370-6ae9c9ee-cc65-11e7-8d4e-18863925b350.png)

**Comment by tarterp** [comment]
I have tried to reproduce. I got this crash only once, and haven't been able to since then. I have run both 32 and 64 bit version. I have run build 10/24/2017, 11/17/2017 and development branch. Can you give more details on how to reproduce.

What build are you using: help->about

![image](https://user-images.githubusercontent.com/3433274/32984774-ea58c3fa-cc7a-11e7-8469-f417c837eafe.png)

A program that could be run and reproduce. Preferably more details on getting there i.e. will it crash with the program at initial breakpoint or should the program be running etc.

**Comment by Chandlr** [comment]
Iam using same build now and same issue everytime.
Well you can for example run Scylla which apparently is not a plugin, sorry my bad.
But having that running while closing x64dbg itself will make it crash.
i can include a sample plugin iam coding on.

[InternetSandbox.zip](https://github.com/x64dbg/x64dbg/files/1485044/InternetSandbox.zip)
goto settings plugins->InternetSandbox->Settings and a form will show
when its open, close x64dbg itself not the form.

**Comment by Chandlr** [comment]
Form close during "DLL_PROCESS_DETACH" fixes the bug, but Scylla still has the "bug"
i might have spoken about this bug before with @mrexodia

**Comment by lynnux** [comment]
I got crash once, by attaching to the crash process, I found that the xAnalyzer cause the crash, after some check, I think when x64dbg close, it will unload all plugins, but if the plugin have extra thread or registed callbacks and not well handled when unloading, it will crash...
