### ISSUE TITLE
Graph in CPU tab

### ISSUE THREAD

**Issue by rokups** [x64dbg/x64dbg#1829]
Be great if we could see graph view inside CPU tab. Then we could still see registers/memory/etc. It would make graph view so much more useful.

**Comment by mrexodia** [comment]
I think I talked about this with @ThunderCls and implemented a prototype, but it caused too much hassle to be nice. Did you try detaching the graph tab?

**Comment by rokups** [comment]
I did, but then it is a floating window without a way to dock it anywhere and even less convenient to use. 

Awesome to hear about prototype and that you were already thinking about such feature. 👍

**Comment by torusrxxx** [comment]
#2389

**Comment by rokups** [comment]
You are a star! Thank you! :pray:

**Comment by ThunderCls** [comment]
It looks really nice! Although I think a couple "fixes" should then make this feature fully usable:

- Follow CIP automatically to graph nodes outside the current function or not rendered yet
- Make stepped on instructions selected when debugging in graph mode instead of the small colored box to the left to make it more uniform with the regular cpu mode debugging (this one could be more of a preference matter)
- Hide the leftmost Qframe when switching to graph mode since currently it's not used (I think) and the space could be used by the graph nodes?

Other than that nice work you guys @mrexodia @torusrxxx

**Comment by rokups** [comment]
To add to that - is it too troublesome to have graph tab have almost identical context menu with cpu tab? You know so there is less disconnect between the two. Also add keyboard shortcuts to the question (i have not tested those much yet).

**Comment by torusrxxx** [comment]
We need to copy code from disassembly to graph in order to add these menus, and both the disassembly and graph source code are already very big. There will be work to extract these common code to a separate file and also make the context menu better.

**Comment by torusrxxx** [comment]
> 
> 
> It looks really nice! Although I think a couple "fixes" should then make this feature fully usable:
> 
>     * Follow CIP automatically to graph nodes outside the current function or not rendered yet
> 
>     * Make stepped on instructions selected when debugging in graph mode instead of the small colored box to the left to make it more uniform with the regular cpu mode debugging (this one could be more of a preference matter)
> 

Sync with origin (`S`)
