### ISSUE TITLE
Errors caused by pdb file

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1853]
os: win 7 x64
x32dbg:snapshot_2017-12-26_13-39

1. Generate exe with latest version vs2017
2. drag exe to debug (exe and pdb must be in the same directory)
3. alt + f2

**Comment by learn-more** [comment]
That is a very in-depth description of 'errors', that will help narrow the problem down for sure.

**Comment by stonedreamforest** [comment]
![2017-12-29_09-10-34](https://user-images.githubusercontent.com/16742566/34427099-259da9e4-ec79-11e7-9dcf-1d84607a0eb1.gif)
@learn-more

**Comment by Mattiwatti** [comment]
This is just a guess, but this may be caused by the obnoxious `/DEBUG:FASTLINK` setting which was made the default in VS2017. See [https://blogs.msdn.microsoft.com/vcblog/2016/10/05/faster-c-build-cycle-in-vs-15-with-debugfastlink/](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/faster-c-build-cycle-in-vs-15-with-debugfastlink/) for info. To get a non-crippled PDB, you need to either set 'Generate Debug Info' to `/DEBUG:FULL` or set 'Generate Full Program Database File' to true (they do the exact same thing - brilliant UX design).

I'm pretty sure dbghelp.dll from the newer Windows 10 SDKs will recognise these PDBs (I don't know if it can get useful info from them, but at least it shouldn't crash). The downside is no more XP support.
