### ISSUE TITLE
Graph ignores INT3

### ISSUE THREAD

**Issue by twifty** [x64dbg/x64dbg#2016]
When graphing a function which internally throws an exception, the graph will include the INT3 lines and include the next function.

Here is a short example from `std::vector`:
```
push sdk.10031788 ; "vector<T> too long"
call sdk.100128EA
int3 
int3 
int3 
int3 
push ebp
mov ebp,esp
sub esp,0x28
push ebx
....
```

This is on the latest windows build.

**Comment by mrexodia** [comment]
There is no way for x64dbg to know that your function is `__declspec(noreturn)`, so it cannot assume an int3 is the end of a function.

**Comment by twifty** [comment]
Why was this closed? A problem clearly exists in the rendering of the graph.

How about giving users an option to right click and remove the unwanted part of the graph? Or allow us select exactly which lines should be included.

Currently any function which uses vector allocate/resize inline methods will cause the next, completely unrelated, function to be included in the graph. This greatly increases the graph size and makes it extremely difficult to follow code flow.

**Comment by mrexodia** [comment]
It was closed because x64dbg doesn’t know what noreturn is and thus cannot assume that int3 is the end of the function.

Often there are int3 instructions in real code (asserts, anti debug tricks) so we cannot say “it’s an int3, so the flow ends here”. This is why the behavior right now is as-expected.

It would be possible to add a data type “terminal instruction” and allow users/analysis to mark the int3. We can turn the issue into that and reopen it if you want.

If you have another problem, please open a new issue on github so it’s easier to track for someone who would like to fix it :)
