### ISSUE TITLE
32-bit malware sample causes x64dbg crash when opening

### ISSUE THREAD

**Issue by rotateLeft** [x64dbg/x64dbg#2065]
Open 32-bit sample

98ece1ba0e548ffb536fffa3e8ea75a2b9d6d8a27e55408d863c5e3d5414890c

With snapshot_2018-10-31_12-52.zip:

<img width="895" alt="screen shot 2018-11-02 at 3 03 21 pm" src="https://user-images.githubusercontent.com/29029736/47893336-9928d300-deb0-11e8-9116-96fd801174cd.png">

**Comment by rotateLeft** [comment]
Malware sample attached. Usual password.
[98ec-x86-gui.zip](https://github.com/x64dbg/x64dbg/files/2541360/98ec-x86-gui.zip)

**Comment by rotateLeft** [comment]
"infected"

**Comment by balintf** [comment]
I've checked this crash and it happens due to a bogus Debug Directory size in the PE headers. The sample contains a Debug Directory with the size 0xfffff000 which causes the while loop in ReadDebugDirectory to overrun the mapped file and crash.

It can be reproduced on a non-malware 32-bit sample (e.g. calc.exe) by using CFF Explorer to modify it's Debug Directory entry's size to 0xfffff000 and the entry's base address so it points to a valid address that's not a supported entry (e.g. to a random position after the original entries).

I have a fix for this and will send a PR shortly. PE reading doesn't seem very robust at the moment, there could be similar crashes with other malicious PE files. @mrexodia, do you have any suggestions on how to review and exercise this part of the code?
I was thinking of trying to setup AFL and/or libFuzzer for fuzzing this part of the code, and trying to find a collection of malformed PE files that could serve as further testcases.

**Comment by blaquee** [comment]
You could try and run a few of the corkami samples through it and see if any of the 'legal malformed' PE's crash the parser somehow. https://github.com/corkami/pocs

**Comment by balintf** [comment]
Thanks! Those samples look promising, I tried running a few manually and no crashes so far, but I'll really have to automate it to properly check all of them.
