### ISSUE TITLE
Error while opening an executable

### ISSUE THREAD

**Issue by Simo56** [x64dbg/x64dbg#2084]
-November 18 2018 version
-Windows 10, service pack 1803
-I try to use x64DBG to inspect a software.exe (IRIS PROJECT, the one for the eyeTracker), but when i try to drag and drop the executable, first it ask me to restart it as an administrator, after that, on the bottom it writes: "Error starting process (CreateProcess, 00000740, uiAccess="true")!"

![image](https://user-images.githubusercontent.com/20564263/48977259-6df06880-f097-11e8-81fc-3a06298b50a3.png)

**Comment by mrexodia** [comment]
You can google for “uiAccess true” and find for example http://techsupt.winbatch.com/webcgi/webbatch.exe?techsupt/nftechsupt.web+WinBatch/Vista+UiAccess~TRUE~and~Protected~Locations.txt

This tells you that in order to gain the uiAccess=true privilege you have to sign the application (x64dbg.exe) with a valid digital signature and place it in a secure location.

If you follow these steps you will be able to debug other applications that require this privilege.

There are also some ideas out there to attach to such a process with the debug privilege enabled, but I honestly doubt that’d work.

**Comment by Aholicknight** [comment]
I am having this same issue. Does anyone know how to fix this?

**Comment by bitraid** [comment]
> I am having this same issue. Does anyone know how to fix this?

Change the `uiAccess` of the  target exe manifest resource (using ResourceHacker or something similar) from `true` to `false`.

**Comment by Aholicknight** [comment]
@bitraid Thank you. Let me point out that this program has some protection as if I set breakpoints on the strings (register); it won't break. But, you solved my problem, so thank you for that.
