### ISSUE TITLE
Error setting breakpoint at 00401000! (memread)

### ISSUE THREAD

**Issue by fredddii** [x64dbg/x64dbg#2099]
For some reason x32dbg is unable to set breakpoints while OllyDbg can. However, I am trying to move away from OllyDbg due to it not being updated any more.

These executables are primarily practice executables. The one attached is the first practice example in the "Reversing for Newbies 01" in the "Reversing for Newbies - Complete" series by Lena.

**Comment by fredddii** [comment]
[reverseMe.zip](https://github.com/x64dbg/x64dbg/files/2746774/reverseMe.zip)

**Comment by mrexodia** [comment]
What os are you using? For me it sets the breakpoint just fine...

![](https://i.imgur.com/UNjosap.png)

confusingly it looks like the thing is being rebased to 00010000, but lpStartAddress is for the image base 00400000

**Comment by fredddii** [comment]
I am using Windows 10 64-bit 1809 UEFI. I have DEP enabled globally ("Turn on DEP for all programs and services except those I select") and I have also enabled "Force randomisation for images (Mandatory ASLR)" in the Windows Security settings which is disabled by default.

**Comment by Mattiwatti** [comment]
I know this is closed, but the reason for this bug is just too funny. [Check it out](https://github.com/markjandrews/wrk-v1.2/blob/daeeb598c7bf091b1370e8875626ad0cb3cd1ec0/base/ntos/dbgk/dbgkobj.c#L1149). The ~~bug~~ feature was introduced in XP (Windows 2000 sets the start address correctly) and lives on til this day.
