### ISSUE TITLE
feature request: Pushing "Enter" on a empty command prompt should repeat the last command

### ISSUE THREAD

**Issue by ianklatzco** [x64dbg/x64dbg#2107]
I've searched through existing issues and haven't found anything relevant.

This is the behavior in gdb, lldb, and windbg — seems like it might make sense for it to be in x64dbg as well?

I am relatively inexperienced with windows dev, but this seems like the sort of thing I would be able to add without much effort. Would it be welcome?

**Comment by mrexodia** [comment]
Personally I would not use this feature. Generally you're not using the command line to do things like stepping, since there are hotkeys. However like you said, it would be easy to implement so a pull request with setting wouldn't be rejected. On the other hand, the code related to autocomplete/history of the command bar is pretty hacky already so the implementation shouldn't make that even worse 😄
