### ISSUE TITLE
[Feature request] Add shortcut for "copy line" action

### ISSUE THREAD

**Issue by bartlomiejduda** [x64dbg/x64dbg#2110]
Debugger version: **Nov 4 2018**

Operating system version: **Windows 7 64bit**

Brief description of the issue
    Hello. I have one small feature request. Could you please add possibility to modify shortcut/hotkey for copying line? I didn't saw it in **Options > Shortcuts** menu. I've attached screenshot for clarity.

Elaborate reproduction steps for the bug/issue being reported: **None**

A short clip or a screenshot clearly showing the issue.
    https://i.ibb.co/fCQNcKb/copy-line-shortcut.png

The translation you are using. Make sure to also test without translation: **English**

Plugins you have installed. Make sure to also test without plugins: **None**

**Comment by Danatobob** [comment]
I'm using x32dbg "Jan 16 2020" version and I wasn't able to copy **anything** to clipboard when using "CTRL+C" or "CTRL+Ins" on the field shown in the OP's screenshot. Now I've found this feature topic and it started to make sense - I assume before making "Copy Line" hotkey customizable, it used CTRL+C by default. Now CTRL+C does nothing on default settings for that field which I think is counter-intuitive as any user would expect that to put at least something to clipboard considering other textboxes process CTRL+C just fine (for example "Copy Selected Lines").
What's worse is that I can't assign CTRL+C to "Copy Line" without removing hotkey from "Copy" action in Shortcuts list. So I have to choose: either I keep "Copy" as CTRL+C and not be able to copy anything using CTRL+C from the mentioned textbox or I only use CTRL+C on that textbox and need to assign some non-standard hotkey for "Copy".
The solution I see is to make hotkeys nonexclusive, so that more than one action can have it. This is how it works right now anyway: "Copy value" in registers have CTRL+C, "Copy selected lines" have CTRL+C, etc., so I guess this is more of a Shortcuts UI change than internal rework.
