### ISSUE TITLE
"Error setting breakpoint at 00000001" from graph

### ISSUE THREAD

**Issue by RaMMicHaeL** [x64dbg/x64dbg#2127]
I'm not sure how to reproduce this, but it happens quite often for me. Other address-related commands, such as "Follow in disassembler", work properly.

![image](https://user-images.githubusercontent.com/4129781/53427461-a46cb500-39f1-11e9-91eb-37d7c0d00a5a.png)

**Comment by raiseman** [comment]
Just noticed that graph breakpoints are broken since that commit.. (have not updated some time) 
Easy fix is to rollback from
`return zoomActionHelper() != 0;`
to
`return zoomActionHelper();`
at line 2145

Actually, I had no any warnings for that part of the code... (QtCreator 4.7.2) 

Furthermore, this code (before zoom mode has been introduced): https://github.com/x64dbg/x64dbg/blob/5162450ff37d823d1713ba7da3ed310bf52817f5/src/gui/Src/Gui/DisassemblerGraphView.cpp#L1665
had the same functionality

**Comment by mrexodia** [comment]
I’m very confused because that callback returns a bool, so there shouldn’t
be any difference in that code. if(value) is the same as if(value != 0)
right?

**Comment by RaMMicHaeL** [comment]
As far as I understand, it returns the address to set the breakpoint on.
https://github.com/x64dbg/x64dbg/blob/58825d4522f06986e09ab17b141204a66e68dd15/src/gui/Src/Gui/BreakpointMenu.h#L12

**Comment by raiseman** [comment]
Yes. It returns the address.
Should I make a pull request for this? If no one sees any bugs left in zoom mode I would remove "beta" from gui option.

**Comment by RaMMicHaeL** [comment]
> Should I make a pull request for this?

Yeah, why not... I could do it too, but I don't have a development environment for x64dbg, so I won't be able to verify the change.

About the feature in general, first of all thanks :) I used it a bit, and there are two downsides compared to the original mode that I noticed:

* When you zoom out to overview (Shift+Z) you can't know where you came from. In the original mode there's the square that indicates the location.
* Zooming out and moving around the graph is slow when the text is visible but scaled down. Not critical, but annoying if the graph is used a lot.

**Comment by raiseman** [comment]
I think Shift+Z can be improved by adding a highlighting of selected block (like IDA does)

As for graph slowing down, the issue requires more in-depth analysis... IDA and Cutter lags much more on my PC.
