### ISSUE TITLE
The style of x64dbg machine language

### ISSUE THREAD

**Issue by bahuwang** [x64dbg/x64dbg#2150]
Is there any difference between the machine language 48:8DAC24 00FFFFFF(x64dbg) and 48 8D AC 24 00 FF FF FF(visual studio)? And why is it show this pattern?
![x64dbg](https://user-images.githubusercontent.com/11907803/56502169-081fe400-6544-11e9-814d-05a895ad8126.png)

**Comment by mrfearless** [comment]
They both show the same exact bytecode. x64dbg however provides a visual cue to separate the instruction part and any value/constant, or address, relative to the instruction being shown.

In the example given and shown in the screenshot -100 is 0xFFFFFF00 (00FFFFFF shown due to endian)

The other separations (the colon : parts) are (I guess) part of the override prefix for the 64bit instruction
