### ISSUE TITLE
any status for 'showing parameter info in stack windows/dump windows' like olly?

### ISSUE THREAD

**Issue by newbieh4cker** [x64dbg/x64dbg#2174]
I've just read #1288, #783, #334

In 2019, looks like this function is still unavailable

any status update??

**Comment by mrexodia** [comment]
Sorry, somehow my message got lost. Progress is already tracked in those issues. Adding phrases like “In 2019 it doesn’t look like this still isn’t available” isn’t gonna help.

**Comment by brandonros** [comment]
Has this feature been added or not? It's a step back from OllyDbg to not be able to tell what parameters are being passed to what function call...

**Comment by mrexodia** [comment]
No, this feature has not been added. The main issue is that we have to build a database of all Windows APIs and their argument types. There are no plans to incorporate this into the stack view, because on x64 this doesn’t make any sense. Right now you can still see the arguments in the arguments view, just not with their names and types.

**Comment by brandonros** [comment]
I'm talking about when a function is called (not necessarily a Windows API) and you know it just had 3 parameters pushed onto the stack, that the ESP + offset references show param1, param2, param3, etc.

**Comment by mrexodia** [comment]
This is shown in the arguments widget above the stack.
