### ISSUE TITLE
Switch to a Free License

### ISSUE THREAD

**Issue by commonbreed** [x64dbg/x64dbg#2218]
GPL-v3.0 is not considered a "free as in freedom" license after the "Stallman era." The conditions of source code disclosure of derivative works and license lock-in detracts from the freedom of this software. Consider migrating to MIT or Apache 2.0.

**Comment by mrexodia** [comment]
Though I agree with you for most cases I think GPL fits this project perfectly. If possible I would probably migrate to MPL, but the amount of code is insane and nobody signed any CLAs so it’s effectively impossible to migrate the license in a legal/ethical way. Additionally it is not possible to use GPL libraries without being GPL yourself so the GPL is the best license for this project because we can use both GPL and Apache/MIT/whatever libraries.
