### ISSUE TITLE
x32dbg crashes when loading specific executable

### ISSUE THREAD

**Issue by ubfx** [x64dbg/x64dbg#2277]
- Debugger version: **x32dbg Jan 16 2020** straight from the repo, no plugins or mods
- Operating system version:
        Windows 7 x64 SP1 and
        Windows 10 Version 10.0.18363 Build 18363

- The debugger crashes upon loading a specific executable [1]

![O3HbDDudpA](https://user-images.githubusercontent.com/30509320/72667413-0d9b5380-3a1c-11ea-9869-1bebc082a063.gif)

- Elaborate reproduction steps for the bug/issue being reported:

1. Start x32dbg in administrator elevated mode (the debugged program requires admin privileges, but the problem persists when not using elevated mode)
2. Load the executable
3. x32dbg crashes

I have no idea if this is an specific anti-debugging trick or if it's a bug in the software.

[1] https://dl.dell.com/FOLDER02754062M/1/E7250A02.exe

**Comment by ubfx** [comment]
Update: The same executable loads without crashing and can be debugged with
**x32dbg Version Jul 19 2018**

**Comment by mrexodia** [comment]
Very weird, the crash happens here:

![image](https://user-images.githubusercontent.com/2458265/72730608-fd0ce980-3b91-11ea-9edc-ba92560313aa.png)

**Comment by Mattiwatti** [comment]
This is caused by the large `e_lfanew value` in the PE header. There are arguably 2 bugs here: a real bug in TitanEngine (see link above for a PR with the fix) and a minor one in x64dbg caused by TitanEngine returning size 0 incorrectly for the exe file:
`modinfo` in `module.cpp` is a typedef for `std::map<Range, std::unique_ptr<MODINFO>, RangeCompare>`, and `RangeCompare` compares the values of `Range`s (a typedef for `std::pair<duint, duint>`).

Easy fix: change
```C++
modinfo.insert(std::make_pair(Range(Base, Base + Size - 1), std::move(infoPtr)));
```
to
```C++
modinfo.insert(std::make_pair(Range(Base, Size != 0 ? Base + Size - 1 : Base), std::move(infoPtr)));
```

A probably more proper fix could be to change `Range` from a typedef to something like this:
```C++
struct Range
{
    Range(duint first, duint second)
        : first(first), second(first < second ? second : first)
    {
    }

    Range(std::pair<duint, duint> pair)
        : first(pair.first), second(pair.first < pair.second ? pair.second : pair.first)
    {
    }

    const duint first;
    const duint second;
};
```
The second version is only correct if all uses of `Range` throughout x64dbg should only ever hold pairs with `a >= b`, so I didn't make a PR for this.

**Comment by mrexodia** [comment]
The issue is closed, but it still needs some manual work before it will be fixed in snapshots.
