### ISSUE TITLE
No "Attach Breakpoint" Event Option in snapshot_2020-11-12_05-12

### ISSUE THREAD

**Issue by STaRDoGGCHaMP** [x64dbg/x64dbg#2528]
![](https://i.imgur.com/YiWzOKE.png#voIMvuzC51Nnblj)

The option is still listed [in the docs](https://github.com/x64dbg/docs/blob/385f2aee6ed2e4a4f87d6be4097bbc923c386305/gui/settings/Events.md#attach-breakpoint).

How can i attach with an attach breakpoint set?

**Comment by mrexodia** [comment]
No, that feature has been removed. The reason is that the breakpoint
requires a thread to be created in the debuggee and this is a way to detect
the debugger.

If you want to stop the execution for some reason, you can press the pause
button. What is your use case for the attach breakpoint?

**Comment by STaRDoGGCHaMP** [comment]
> What is your use case for the attach breakpoint?
I was reversing some malware that I could only attach to. Starting the malware with a debugger was not really possible without things getting too annoying. The malware was constantly running some anti-debugging logic loop that would terminate the process as soon as I was attached. I had to get lucky by pressing the pause button as fast as possible after attaching, which was a bit annoying. I then discovered the anti-debugging logic and removed it.

**Comment by rmi1974** [comment]
https://github.com/x64dbg/x64dbg/issues/2525 ("Snapshot 2020-11-12_05-12 broke debugging via attach-to-process in Wine ('safe attach' is now default, no longer configurable)") is related since Wine also relies on the standard method.

Wine follows the way Windows debugging API implements process attaching:

*debugger process:*

* DebugBreakProcess
* DbgUiIssueRemoteBreakin -> sends APC to target process (APC_BREAK_PROCESS)

*target process:*

* invoke_system_apc
* APC_BREAK_PROCESS handler -> NtCreateThreadEx ( ... DbgUiRemoteBreakin)

*remote debugger breakin "breakpoint" thread:*

* DbgUiRemoteBreakin
* if (NtCurrentTeb()->Peb->BeingDebugged)  call DbgBreakPoint()
* breakpoint thread exit

But I guess there were too many DbgUiRemoteBreakin detection / bypass methods? ;-)

**Comment by mrexodia** [comment]
Unfortunately there are quite a few. You can hook a few functions in ntdll
that will be executed whenever a new thread is created (so even if you
allocate your own page with an int3 you are not safe). These could
potentially be bypassed if you hijack the thread before creation, but it
requires direct syscalls and is too much of a pain.

Additionally there are various weird bugs in ntoskrnl that allow you to
detect a new thread being created without any way to bypass it, so the
safest option is to not break at all.

ScyllaHide should have been fixed and the debugger can be hidden on time.
