### ISSUE TITLE
[Additional theme request] 

### ISSUE THREAD

**Issue by Dump-GUY** [x64dbg/x64dbg#2548]
Is it possible to add another build in themes like I created here? https://github.com/Dump-GUY/x64dbg---Dark-Theme

Thank you ☺️

**Comment by mrexodia** [comment]
[Dump-GUY.zip](https://github.com/x64dbg/x64dbg/files/7811527/Dump-GUY.zip)

Currently I don't want to add any other themes because if there are any bugs in them I'll have to fix them, but you can copy this folder in the `themes` folder and it will show up in the menu. Hopefully at some point there will be a theme repository and a way to download user themes.
