### ISSUE TITLE
[Complete begginer question, but might be bug in program] String search doesnt search the string

### ISSUE THREAD

**Issue by fikawka** [x64dbg/x64dbg#2594]
Hello, so the issue is that i made an string search and it doesnt search a string, even thought i am sure it exists in application.
I read some old issue in github, and it was that there is sometimes problem, with non english applications but thats not the case.
I believe that there are 2 options in my issue:
1: There is some sort of obfuscation in the application (not even sure if people do obfuscate c++ code and how),
OR
2: The strings are not displayed correctly, the search also is bad.

When browsing like all the strings, i see normal ones like:
,,Unknown exception" etc and extremely weird ones like:
,,MZ" + some chinese character.
The thing is when i search for strings i actually need, they simply dont pop out.
Any ideas what i can do?

**Comment by mnemonic-re** [comment]
There are quite a few reasons why you cannot find the string... It is probably not x64dbg fault. 
Since this is a generic question without any information to go on I can only offer you a few things to look for:

- Program has not yet reached the point where string is loaded
- string is in a Resource file \ segment
- string is being obfuscated (stack strings, custom encryption, known encryption (base64...), etc))
- string is in a different file (borland bpl files for example or a dll)

The string you seek is loaded, it is just a matter of how and when. Since you cannot find it in quickly by normal search, try backtracking a little in the function that is supposed to use the string and step through code to see what is happening. Also you can try the plugin: https://github.com/horsicq/stringsx64dbg

**Comment by torusrxxx** [comment]
A bug with string searching has been fixed.
