### ISSUE TITLE
Debugging pause causes all desktop Windows to be unresponsive

### ISSUE THREAD

**Issue by CyberAsbeel** [x64dbg/x64dbg#2773]
### Operating System

Windows 10 64bit 19042.804

### x64dbg Version

Jul 1 2021

### Describe the issue

Hey, is there a user from China? When I debug the program, if MY current input method is Sogou Chinese input method, when the program pauses, such as when I step into or step out, the debugger window may go into unresponsive state.At this time, if I try to switch to another application window and use it, I will find no response state. Everything is normal when I use Microsoft input method, I am not sure whether x64DBG or Sogou input method is the problem, and I do not know how to determine the specific cause, terrible

### Steps to reproduce

1. Use the Chinese Sogou Pinyin input method
2. Debug a program by continuously entering the debug pause state, such as continuously step into or step out

**Comment by qcq** [comment]
after a really long time, have see this almost same issue.
I am from china HZ.
I also noticed the win10 not response after upgrade to win10 20H2, which make me crazy, 
I notice that my chrome and edge not response, but firefox works well.
I tried to reinstall the 20H2, also reinstall chrome, which has no effect,
after one colleague point that sogou is the root cause.
so I remove it, then everything comes normal.
so I think which should be sogou used some old API.
