### ISSUE TITLE
Build Environment for x64dbg

### ISSUE THREAD

**Issue by elicn** [x64dbg/x64dbg#319]
The detailed instructions and dependencies for building x64dbg make it difficult to contribute. It would be great if there was a VM that consists of all the required dependencies and scripts to make it easier for others to jump in.

**Comment by mrexodia** [comment]
Don't see what's to hard. You don't need to build the dependencies yourself
(in fact you should not unless you want to modify them). You only need Qt,
Visual Studio 2013 with MFC and Windows 7 or higher. I can distribute
neither windows, nor visual studio so that image would become very empty.

Just take the binaries from the latest snapshot and only build x64dbg.

**Comment by mrexodia** [comment]
closing it for now, feel free to reopen (but I'm also subscribed to everything, so commenting works as well).

**Comment by elicn** [comment]
Fair enough; I'm out.

**Comment by mrexodia** [comment]
Obviously I will help you set up a build environment, I will come on TeamViewer personally if it helps the project :)

**Comment by Nukem9** [comment]
@elicn If you really wish to contribute I can set up a VM image. You just need a fast enough internet connection. I don't know of any website to upload a large file like that.

**Comment by mrexodia** [comment]
how about http://mega.co.nz ? it allows up to 50 GB in total if I'm not mistaken
