### ISSUE TITLE
about StepOver

### ISSUE THREAD

**Issue by onesbug** [x64dbg/x64dbg#321]
hi.

i have an idea about stepover in titanengine.
some code like this:
**********************************
label1:
add dword ptr ss:[esp],1
...othercode
retn xx
...
call label1
nop
...othercode
***********************************
if we use like BPX in StepOver function will not be able to properly hit.
Maybe we can use a memory breakpoint on [esp].
then hit it when exception instruction is like "retn"

This is very useful for debugging junk code.

**Comment by mrexodia** [comment]
luckily we don't use a BPX in StepOver unless it is actually needed (`call` or `rep` instructions). https://bitbucket.org/mrexodia/titanengine-update/src/master/TitanEngine/TitanEngine.Debugger.Control.cpp?#cl-75

**Comment by onesbug** [comment]
i don't think so.

![1111](https://cloud.githubusercontent.com/assets/10548054/8266965/0155061e-177d-11e5-8198-ca8e906548b6.png)

When I step over in addr:01346D60,i can't stop in 1346D64,it flew.
Just an improved idea,If it is useless,forget it :)

**Comment by mrexodia** [comment]
Right, thought you were talking about the `ret` instruction. there is no way to detect if a call is going to return or not (this is called the halting problem). Therefore you should use 'StepInto' instead. Memory breakpoint on [esp] is possible, but it would break on a shitload of things, since you cannot memory breakpoint on less than 0x1000 bytes.

**Comment by onesbug** [comment]
since you cannot memory breakpoint on less than 0x1000 bytes.

ok,i see.indeed.
