### ISSUE TITLE
Seems to be being detected by Crowdstrike as tamporing with the Flacon Sensor [INFO]

### ISSUE THREAD

**Issue by t3hbb** [x64dbg/x64dbg#3267]
### Operating System

10 PRO 22h2 19045.3570

### x64dbg Version

2023-11-02_17-30

### Describe the issue

I am aware it is a false positive. I just wanted to report that it was being blocked by Crowdstrike

### Steps to reproduce

1. Install Crowdstrike
2. Download x64dbg
3. Attempt to run x64bdg or x32dbg

### Attachments

![image](https://github.com/x64dbg/x64dbg/assets/21687763/2a2d62b5-fc5c-4a81-83b6-bcaa8c8b3ced)
![image](https://github.com/x64dbg/x64dbg/assets/21687763/dfcbe8a4-b13c-48f1-b1dc-f11c37dbb98e)

**Comment by mrexodia** [comment]
Most likely a stupid knee-jerk reaction to a DLL side loading “vulnerability”. Just report windbg.exe to them as well: https://x.com/mrexodia/status/1630320327967252483?s=46&t=0Ven6DWZeNPcGOTNyWx89g

The DLL side loading has since been fixed in x64dbg by validating the signature of all loaded dependencies. There is nothing more I can do 🤷‍♂️
