### ISSUE TITLE
issue with hardware breakpoints

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#329]
1. place hwbp after current cip
2. run
3. 'bphwc'
4. run again

it will crash on STATUS_SINGLE_STEP

**Comment by onesbug** [comment]
INT3 breakpoint "entry breakpoint" at 54DFA1D1!
Hardware breakpoint at 54DFA1D1 set!
Hardware breakpoint (execute) at 54DFA1D1!
All hardware breakpoints deleted!
First chance exception on 54DFA1D2 (80000004, EXCEPTION_SINGLE_STEP)!

No crash,it will be caught by the debugger,but it's interesting

**Comment by mrexodia** [comment]
It's a simple bug in titanengine I think

**Comment by a554335752** [comment]
I got the same problem.   - -!
sometimes it will crash on STATUS_SINGLE_STEP

**Comment by Herz3h** [comment]
The problem is that you set the Trap flag before calling the hardware callback and if the user deleted breakpoint and the callback returns, the trap flag is still set but debug registers are cleared which makes it think the debuggee throws the exception

**Comment by mrexodia** [comment]
Just tried and seems to be fixed.

**Comment by M-o-o** [comment]
I sometimes see something like this. Updated to latest snapshot 2019-05-19 and still happening occasionally... Debugger doesn't crash, but program exits. It may be related to using commands or logging with hardware breakpoints, or perhaps manually stepping through commands that trigger the breakpoint. I'll try to narrow how to reproduce it at some point, but perhaps the cause is easy enough to see anyway.
```EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: 80000004 (EXCEPTION_SINGLE_STEP)
          ExceptionFlags: 00000000
        ExceptionAddress: 000000014126A2B1 myexe.000000014126A2B1
        NumberParameters: 0
First chance exception on 000000014126A2B1 (80000004, EXCEPTION_SINGLE_STEP)!
