### ISSUE TITLE
all patches applied but no change in the "patched" file itself

### ISSUE THREAD

**Issue by addressnopping** [x64dbg/x64dbg#3323]
### Operating System

Windows 10 64bit

### x64dbg Version

Jun 30 2023

### Describe the issue

im debugging a dll, when i click on "Patch file" it says all patches have been applied, but there is no change between the original dll and the "patched one"

### Steps to reproduce

1. a
2. a
3. a

**Comment by mrexodia** [comment]
It’s not enough information to reproduce the issue. What DLL and where did you patch?

**Comment by addressnopping** [comment]
its kinda private, but im trying to bypass the security (educational purposes) and the dll has no protection. nopped some instructions on the dll.

**Comment by addressnopping** [comment]
the only way i found to "apply" the patches was by dumping the dll using scylla (tried to use external programs to apply the .1337 file but they seem to just replicate the file)

**Comment by mrexodia** [comment]
Could you email the information to private-3323 [at] x64dbg.com? I’ll keep it private

**Comment by mrexodia** [comment]
Any updates? If you do not want to share the whole file I could also attempt to reconstruct it if you give the following information:

- First 0x400 bytes of the file (the headers)
- VAs you tried to patch

I would really appreciate if you could share this information (or the full DLL at the email I provided), because this code is really old and didn't have any bugs at all up to this point...
