### ISSUE TITLE
x64gb does not detect any method

### ISSUE THREAD

**Issue by x3x0z** [x64dbg/x64dbg#3393]
### Operating System

Windows 11 / Parallels MAC M2

### x64dbg Version

Jul 12 2024

### Describe the issue

My X64GB does not detect methods like _strcmp or any function name, it is showing the raw exadecimal:
call c8173b
when should it show:
call _strcmp

To help with the debugging, I am following some videos of SOLID and some friends and it appears to everyone except me, why is this happening?

My x64dbg:
![image](https://github.com/user-attachments/assets/a8e7fe6c-7963-4b18-9f6c-59b525c41179)

his x64dbg
![image](https://github.com/user-attachments/assets/3477069c-9d3a-41a1-929f-cf08c748e27b)

We are debugging exactly the same file and they are the same instructions, I want it to appear with a name like the light theme.

I have checked the symbols and are ok

![image](https://github.com/user-attachments/assets/270e5738-6999-4253-a9ef-122f01354132)
![image](https://github.com/user-attachments/assets/377353a0-5cfa-462d-ba5e-515251aa5d96)

### Steps to reproduce

1. Debug a file
2. Go to line what you want
3. i cant see function names.

**Comment by mrexodia** [comment]
I will add a warning message, but you cannot reliably debug x86 code on Windows for ARM. Most likely it's because the ARM PE files aren't parsed properly, but I have no plans to fix this. You should use an x86 computer to debug x86 code, or try some usermode emulation like https://getwhisky.app/ via Wine.
