### ISSUE TITLE
Trace to a specific point

### ISSUE THREAD

**Issue by gameplayoffert** [x64dbg/x64dbg#3501]
### Feature type

Quality of life

### Describe the feature

Hi, i'm not sure if that feature already exist or not, if yes then i wasn't able to find it but it will be really good if we were able to trace from a specific point to an other specific point without pressing "F7" everytime. Because depending on the code, it can be really long especially for loops.

**Comment by mrexodia** [comment]
1. Set a breakpoint where you want to stop
2. Start a trace without condition

**Comment by loqstrz** [comment]
> 1. Set a breakpoint where you want to stop
> 2. Start a trace without condition

This is how I've done it and it does not record the trace for me. Does this only apply within the same function or can I set a breakpoint somewhere else (in the same symbol though) ?

Perhaps I am doing this wrong though. I always just enable highlighting and then when I press F7 it records it, but otherwise as stated above it doesn't.
