### ISSUE TITLE
Wrong behavior in binary edit window

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#367]
1- Select a sequence of bytes in the disassembly / dump window
2- Right click -> Binary -> Edit
3- In the ASCII or the UNICODE text box type a character (in the middle or beginning)
4- The typing cursor immediately jumps to the end of the text box

If this is not a wrong behavior (this is how x64dbg works) could you please change it
so that it jumps to the next character like any text editor ?
It gets really annoying especially if you want to edit a long string.

EDIT: after some more tests, it also seems to be pushing the characters to the right
1- Edit for example a string of 5 characters / bytes (example: `"Hello"`)
2- Make sure the switch __`Keep size`__ is selected and place the cursor exactly before the
3rd char
3- Type any char (example: `Z`, so the new string would be `"Hezll"`)
(you can already see at this step that the first 'L' was not replaced but instead pushed to the right)
4- Now place the cursor at the beginning of the string and type another char (example: `X`,
so the new string is: `"XHezl"`)
5- You can clearly see that the char 'H' was not replaced with `X`
but instead the whole string got pushed to the right.

**Comment by wk-952** [comment]
Another thing related to this, if you edited a string that contains null bytes `0x00`,
those null bytes will be replaced by `0x2E` (dot character).

*Expample:
- Consider this string (as ASCII) "__`string1.string2.`__" (where the 2 dots are null terminators`0x00`)
1. Edit this string in the dump window `(Ctrl + E)` then replace any char in the ASCII textbox.
2. Notice in the hex textbox that the `0x00` was replaced with `0x2E`.

ASCII strings when edited in the Unicode textbox will face the same behavior,
but only the odd-ordered chars are replaced, while even-ordered ones will stay `0x00` as they are.

The tricky part is that this happens because english chars consume only 1 byte,
so it'll always be 0x__??__ concatenated with 0x00.

**Comment by Atvaark** [comment]
I also noticed this behavior when editing some strings.

The cursor position is set to the end of the text box because a **single** change in either the ASCII or the Unicode QLineEdit will update the text in **both** QLineEdits. Only the QLineEdit that didn't emit the textEdited signal has to be updated. 

The quick and dirty solution would be to save the cursor position, update the text and then restore the cursor position. With this change the QLineEdit will behave like normal text boxes in *insert mode* (*).
[HexEditDialog.cpp#L126](https://github.com/x64dbg/x64dbg/blob/60f2537c20361def330f829c0bb56e01378c64e9/src/gui/Src/Gui/HexEditDialog.cpp#L126)

```
void HexEditDialog::on_lineEditAscii_textEdited(const QString & arg1)
{
    Q_UNUSED(arg1);
	int cursorPosition = ui->lineEditAscii->cursorPosition();
	on_btnAscii2Hex_clicked();
	ui->lineEditAscii->setCursorPosition(cursorPosition);
}

void HexEditDialog::on_lineEditUnicode_textEdited(const QString & arg1)
{
    Q_UNUSED(arg1);
	int cursorPosition = ui->lineEditUnicode->cursorPosition();
    on_btnUnicode2Hex_clicked();
	ui->lineEditUnicode->setCursorPosition(cursorPosition);
}
```

\* But this won't solve the issue with pushing characters to the right when **Keep size** is checked and there are already *mHexEdit->data().size() / sizeof(char/wchar_t)* characters in the QLineEdit.

What is missing from the QLineEdit is an **overwrite mode** (which only works when setting an input mask at the moment).

**Comment by wk-952** [comment]
This is solved, the only problem now is that when `Keep Size` is selected you have to highlight the chars you want to replace (overwrite mode is no automatically toggled) which could be simply solved by pressing `Insert` on the keyboard (manually toggle overwrite mode).
Thanks @Atvaark.
