### ISSUE TITLE
callstack not doing anything right now

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#372]
not sure if related to any of the callstack commits or maybe I messed stuff up somewhere.

**Comment by wk-952** [comment]
I tried rebuilding with older commits and this seems to be introduced since commit eac21d6
previous commit (exactly before this one) is fine.

**Comment by mrgreywater** [comment]
Debugged a little myself, the reason is that it only checks for <code>PAGE_EXECUTE</code>, but doesn't check for the flags <code>PAGE_EXECUTE_READ</code>, <code>PAGE_EXECUTE_READWRITE</code> or <code>PAGE_EXECUTE_WRITECOPY</code>.

Replace the [Line 364 in stackinfo.cpp](https://github.com/x64dbg/x64dbg/commit/eac21d6a3b142b1916ff62e26c1d5c54e8e14ccb#diff-8cb4a083758bd2986c8efcb3776c1833R364) with 
<code>return (pageInfo.mbi.Protect & (PAGE_EXECUTE | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY)) != 0;</code> 
to fix it. I might can create a pull request, but it would be easier if somebody with repo right could push the fix themselves.
