### ISSUE TITLE
disasm error

### ISSUE THREAD

**Issue by 9844201** [x64dbg/x64dbg#411]
![default](https://cloud.githubusercontent.com/assets/3508145/10564789/8a11b414-75f3-11e5-8935-65b875677180.jpg)

**Comment by mrexodia** [comment]
Hello, What you're looking at is not an error. There is just an address
alignment mismatch.

**Comment by wk-952** [comment]
About this address alignment mismatch, i face it more often too (also with olly),

if by chance a `call / jump` instruction pointed to an address in the middle of a misaligned code
and you stepped-in this instruction, the disassem window will be forced to display the correct
code/allignment, but once you scroll up/down the misaligned code will appear again.

So my question would be: is there any workaround for it ? anything we can do about it ?
i've been roaming the internet since i was using olly (almost a year ago) for any brief
explanation/workaround, but my lack of knowledge didn't get me anywhere.

You don't have to answer this in details or anything, just a simple yes or no answer is
fair enough for me, or if you could, please link me a website where i can start reading about it.
I would be very grateful to you for any answer.

**Comment by mrexodia** [comment]
You cannot do much about it if the code was put like that on purpose (like obfuscated code). However, it would be possible to flag data in a specific way to force the code to align like that, but it's not pretty.

Something that might help is using the Num +/- keys to navigate to the previous selected location.

The only reason this exists in x86 is that instructions have multiple sizes (and thus the processor cannot really enforce some alignment to prevent this).

Hope that helps.

**Comment by wk-952** [comment]
Yes! you've helped me very much actually, i started searching immediately for x86 instructions
sizes, and this seems to explain a very similar scenario [Interesting Behaviors in x86 Instructions] (http://d0cs4vage.blogspot.com.eg/2011/04/interesting-behaviors-in-x86.html) .

As a very quick test, the EntryPoint instruction of the 32-bit version of Cheat Engine v6.4
is misaligned, the instruction exactly before this one is 1-byte long `00`, so any debugger
while parsing the opcodes would consume the next byte and concatenate it to this `null byte`
to form a valid instruction `00 C6` and of course this byte 'C6' is from the next instruction.

Assuming all of this is true and after reading this blog i can safely assume that 'C6' is the prefix of
the EntryPoint instruction, but of course it's eaten in the previous instruction resulting in the weird
looking code, as a solution to force `C6` to be the prefix i thought immediately of NOP-ing that
`null byte` since NOP is one of the valid 1-byte instructions and it would force the debugger to
concatenate the `C6` to the next instruction,
surprisingly it worked! and the code now looks normal as it should be without worrying about
scrolling up/down in the disassem window.

So thank you again so much mrexodia for taking the time to respond to this, you've helped me a lot.
