### ISSUE TITLE
issue with assembling certain instructions (XEDParse)

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#432]
this video should explain it (didn't try myself)
https://mega.nz/#!y0RwURpA!F8NTi90Vggetz5zILaw7ZYh0cAZm0WNuqXQcgQHBPfA

**Comment by wk-952** [comment]
I might have some useful information regarding __specifically__ the issue shown in this vid,
actually i wanted to open an issue for this to point it out but wasn't sure about it.

XEDParse is not actually the issue, it's perfectly fine at this point!
Since - i guess - capstone commits or before that by just a little, you introduced some sort of a
confusion, the short description of it would be:
instructions with pointer-operands referencing the stack `(dword ptr SS:[esp])`, will __always__ display `SS` as `DS`.
So instructions like this:
`cmp/mov/add dword ptr SS: [esp + xxx], xxx` will always be displayed as:
`cmp/mov/add dword ptr DS: [esp + xxx], xxx`, but in fact they're still using `SS`
and this is where the confusion came from.
Moreover, you decided to hide `DS` from the "Assemble at .." window whenever it's used.

*Explanation:
In the old build, the instruction was shown as:
`mov dword ptr SS:[ebp - 428], 0` (displays `SS` correctly as expected)
so when he pressed `space`, the stack segment register `SS` was already typed in
the "Assemble at..." window   --->   no problem
but in the new build (after the confusion was introduced), the instruction was shown as:
`mov dword ptr DS:[ebp - 428], 0` (not displaying `SS` but it's actually using it)
so this time when he pressed space, `DS` was being used (and of course hidden from
the "Assemble at ..." window), and he actually assembled the new instruction with `DS`
while the original one was using `SS` (but not displaying it).

This is why the new instruction had a different size, and of course to compensate the difference
one byte from the next instruction was eaten and the rest of it was filled with `NOP`s

You can reproduce this very easily actually:
1) Type something like: `mov dword ptr SS:[esp - 20], 4`,
   It will be displayed as: `mov dword ptr DS:[esp - 20], 4` (wrong)
   and will have the opcode: `C7 44 24 E0 04 00 00 00` (8 bytes)
2) Type: `mov dword ptr DS:[esp - 20], 4`,
   It will be displayed as: `mov dword ptr DS:[esp - 20], 4` (correct)
   and will have the opcode: `3E C7 44 24 E0 04 00 00 00` (9 bytes)

- In the latest build, If you replaced the current version of XEDParse with a very old one
you'll still face this issue, that's why i told you above that it;s not a XEDParse issue.

**Comment by wk-952** [comment]
Ah, forgot to mention that if the referenced register was anything other than `esp`,
`DS` and `SS` seems to be displaying correctly.
As a quick example, this: `mov dword ptr SS: [eax + 5], 9` will display `SS` correctly.

**Comment by mrexodia** [comment]
@wk-952 thanks a lot for your in-depth explanation. one point is weird though, XEDParse uses SS automatically if you assemble `mov dword ptr [esp - 0x20], 4`

related https://github.com/aquynh/capstone/issues/473 (capstone uses implicit segments based on the base register and doesn't set them in their structure) should be easy enough to fix.

**Comment by wk-952** [comment]
Looks pretty much fine now :+1: , all pointer-operands referencing the `esp` will display `SS` correctly as their default segment register,
also pointer-operands that reference the `esp` and use `SS` will also be displayed correctly (previously that didn't happen).

Also now when you press `space` the "Assemble at ..." window will use `SS` by default if your pointer-operand uses the `esp` register.
