### ISSUE TITLE
STI/Breakpoint slow

### ISSUE THREAD

**Issue by dummy0stud** [x64dbg/x64dbg#458]
I'm doing some tests with step into and It looks like it's super slow, is this problem related to titan engine?

In some of my other tests I need 2 set about 900 breakpoints(int3)(using DbgCmdExecDirect and DbgCmdExec), it is really slow and x32dbg deadlocks if I use DbgCmdExec after setting 255 breakpoints, using DbgCmdExecDirect I can set it with success but it's super slow!

What's the difference between DbgCmdExecDirect and DbgCmdExec, are debugging functions documented somewhere?

**Comment by Nukem9** [comment]
Single stepping is slow because the most of the GUI is re-drawn for each step.
I don't have an explanation for the slow breakpoint commands.

`DbgCmdExecDirect` is synchronous and executes a command on the _current_ thread.
`DbgCmdExec` is asynchronous and queues a command to be run on the dedicated command thread.

**Comment by mrexodia** [comment]
I have an explanation for slow breakpoint commands. A vector is used I
think to store the breakpoints so insert is O(n). This kind of stuff will
be fixed once we get a new engine which will take a long time...
