### ISSUE TITLE
SEH/VEH viewer

### ISSUE THREAD

**Issue by neoxquick** [x64dbg/x64dbg#489]
Hello i would really like if you can add this option to debuger..

bye Neo

**Comment by Nukem9** [comment]
For later.

Structured Exception Handling (32-bit only)
--------------
First/top link is located at `fs:[0]` and declared as `PEXCEPTION_REGISTRATION_RECORD`. [Definition here](http://www.nirsoft.net/kernel_struct/vista/EXCEPTION_REGISTRATION_RECORD.html).
See slide 5 [here](https://www.exploit-db.com/docs/17505.pdf) for layout.

Vectored Exception Handling
--------------
Windows XP: Stored in `ntdll!RtlpCalloutEntryList`
Windows Vista+: Stored in `ntdll!LdrpVectorHandlerList[0]`
Both declared as `VECTORED_EXCEPTION_NODE`.

`Handler` must be decoded with [the remote process cookie](http://doxygen.reactos.org/dd/dc6/lib_2rtl_2process_8c_ad52c0f8f48ce65475a02a5c334b3e959.html) to get the real address.

Vectored Continue Handling
--------------
Windows XP: ???
Windows Vista+: Stored in `ntdll!LdrpVectorHandlerList[1]`

See above VEH.

Unhandled Exceptions (SetUnhandledExceptionFilter)
--------------
Windows XP: ???
Windows Vista+: `kernelbase!BasepCurrentTopLevelFilter` callback must be decoded with process cookie.

**Comment by Avinm** [comment]
Forked and implemented for 32-bit. (https://github.com/Avinm/x64dbg/)
![viewer](https://cloud.githubusercontent.com/assets/11731803/14059451/cbc6fec8-f366-11e5-8c90-4bc9bb2cbc03.PNG)
![stack](https://cloud.githubusercontent.com/assets/11731803/14059453/d43aa780-f366-11e5-9bc1-9b4ce7395f6d.png)

**Comment by mrexodia** [comment]
SEH is imlemented but x64 SEH (which is in the PE header) and VEH etc are not implemented.

**Comment by mrexodia** [comment]
Anybody know how to get the remote process cookie on Windows XP? NtQueryInformationProcess denies access if hProcess isn't the current process.

**Comment by mrexodia** [comment]
Implemented fully through the `exhandlers` command.

**Comment by Mattiwatti** [comment]
Where are you people getting these magical NtQueryInformationProcess's that return a cookie for any HANDLE other than NtCurrentProcess? I have Windows 7 and even with debug privileges and a PROCESS_ALL_ACCESS handle I can't query the cookie of another process.

I checked in IDA to be sure, and not only does the handle need to be to the current process, it literally has to be (HANDLE)0xFFFFFFFF. Any other value gives STATUS_INVALID_PARAMETER (0xC000000D), even if it is a valid (non-pseudo) handle to your own process. I checked ReactOS since the comment in MemDecodePointer references it, and they have the same implementation:
```C++
if (((ProcessInformationClass == ProcessCookie) ||
    (ProcessInformationClass == ProcessImageInformation)) &&
    (ProcessHandle != NtCurrentProcess()))
{
    /*
     * Retrieving the process cookie is only allowed for the calling process
     * itself! XP only allows NtCurrentProcess() as process handles even if
     * a real handle actually represents the current process.
     */
    return STATUS_INVALID_PARAMETER;
}
```
Then I tried it on Windows 10 in a VM and there it works perfectly fine. Disassembly of ntoskrnl.exe shows that you can now do it if you have 0x20 = PROCESS_VM_WRITE access. I don't have Windows 8 to try so I can't say what happens there, but it definitely doesn't work for me on 7.

**Comment by mrexodia** [comment]
Yeah indeed I don't know how to get the process cookie in those os
versions...

**Comment by Mattiwatti** [comment]
Well on my Windows 7 VM I got around it by simply patching ntoskrnl.exe to always set the cookie to a constant 0 regardless of who is calling the function. Of course this is insane, but that VM has so many kernel patches by now that there is no concept of security left anymore anyway. Amazingly enough this works totally fine: not only does the OS boot, I tried running some protected unpackmes and none of them noticed this strange implementation of EncodePointer. On XP I got the same result which is even funnier because RtlEncode/DecodePointer on XP is simply ptr ^= cookie.

Anyway, I'm guessing the above approach is a bit extreme for most people, so I tried doing the same thing in ScyllaHide (it already has an NtQueryInformationProcess hook) and that seems to work perfectly fine also, though I only tried it on a dummy VEH program. Though you might run into issues if early system DLLs (ntdll, kernel32) store encoded pointers before ScyllaHide hooks the syscall and then try to decode and reuse them later. I don't know if they do this.

Unfortunately, short of hooking NtQIP or patching the kernel it doesn't seem like there are many other options. Anything related to SEH/VEH goes through [Rtl]Decode/EncodePointer, and those are just wrappers for NTQIP anyway. One alternative might be to create the target process suspended and use CreateRemoteThread/NtCreateThreadEx to obtain the cookie from ntdll remotely before resuming the main thread. But... that doesn't actually sound better at all, does it? Eurgh.

If your target allows for it I would stick to just adding some assembly with Multimate to retrieve the cookie at process start and then jmp back to OEP. But I can't think of any way to do it by only changing the pointer decode function in x64dbg.

**Comment by mrexodia** [comment]
Yeah, injection seems to be the way sadly...

**Comment by Mi4uric3** [comment]
Take a look at KUSER_SHARED_DATA.cookie (offset 0x330) which is available since late 5.1, late 5.2 and higher. Info: http://www.geoffchappell.com/studies/windows/km/ntoskrnl/structs/kuser_shared_data.htm

**Comment by Mattiwatti** [comment]
The cookie in KUSER_SHARED_DATA is a different one; it's system-wide and used by Rtl[Encode/Decode]SystemPointer. The SEH/VEH cookie is per-process. Both cookies are write-once and set by the kernel, but the per-process cookie can only be queried by the process that owns it.

**Comment by Mattiwatti** [comment]
Having looked at this problem some more, there seem to be some convenient aspects to the way ntdll does process initialization that might make this solvable:
- The earliest code that runs in every user mode process is the LdrInitializeThunk APC, which (eventually after some basic checks) ends up in the real initializer **LdrpInitializeProcess**. (LdrpInitializeProcess is also the function that calls LdrpDoDebuggerBreak, the 'system breakpoint', but that happens much later).
- The very first thing LdrpInitializeProcess does is call **RtlSetUnhandledExceptionFilter** with an argument of... 0. This is what RtlSetUnhandledExceptionFilter looks like:
```asm
RtlSetUnhandledExceptionFilter proc near
sub     rsp, 28h
call    RtlEncodePointer
mov     cs:RtlpUnhandledExceptionFilter, rax
add     rsp, 28h
retn
```
- You can probably see where this is going. **RtlpUnhandledExceptionFilter** now contains a value that was encoded with a known input, so we can get the cookie back from this.

I think it should be possible to automate this retrieval in the debugger engine, so that the cookie value will always be known without a need for hooking or injection. It's also more reliable because there is no chance for DLL initializers to install exception filters before the hook is in place.
