### ISSUE TITLE
Using attach to a process as a first action doesn't load db file

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#493]
1. Make sure you have a `.ddxx` file for any program (specially breakpoints)
2. Open this program without the debugger 
3. Start **x**??**dbg.exe** and attach this process.
4. BPs are not loaded (probably the whole database file isn't loaded).
5. Open this application from the debugger ---> BPs are loaded normally.

- After that, if you attached the same process again BPs will be loaded again normally,
so the issue is using `Attach` as a first thing when you open the debugger.

**Comment by Nukem9** [comment]
Reason: it's inferred that `cbCreateProcess` will always be called. On attach a process is _not_ created, so the function is never called. `cbCreateProcess` calls `DbLoad`.
Fix: Add `DbLoad` to `threadAttachLoop`.

@wk-952 any idea how long this bug has existed? I don't think debugger attaching code has been modified in a long time. Seems like this bug was missed for a while.

**Comment by wk-952** [comment]
No sorry, but i do have a very old build `x64_dbg v0.24_dev_build(2-20)` that doesn't seem
to have this issue.

**Comment by Nukem9** [comment]
There's no need to check where. I was just wondering if you knew or not. (I can check myself).

**Comment by mrexodia** [comment]
I thought cbCreateProcess was called. However maybe the bug was introduced
somewhere because I did copypasta the attach and process callbacks.

**Comment by Nukem9** [comment]
see: https://github.com/x64dbg/x64dbg/commit/81117392ecd37e8dcc53b25326145d3cfaf39c9f

**Comment by wk-952** [comment]
Fixed, thank you very much.
