### ISSUE TITLE
Attach to suspended process failure

### ISSUE THREAD

**Issue by 500mhz** [x64dbg/x64dbg#635]
[samples.zip](https://github.com/x64dbg/x64dbg/files/241907/samples.zip)

![screen shot 2016-04-29 at 07 33 15](https://cloud.githubusercontent.com/assets/10212432/14910037/a1d8bb82-0df2-11e6-964b-ab0620cef956.png)

Run test.exe , test.exe run test2.exe (CREATE_SUSPENDED) and try to attach (x32dbg.exe) to test2.exe

**Comment by Nukem9** [comment]
Reproduced. This only happens when a process is created and not when manually suspending with `Process Hacker->Suspend Process`.

Reason: Process hasn't been initialized. PEB isn't initialized. Ldr isn't fully initialized.
![image](https://cloud.githubusercontent.com/assets/4228359/15792694/de0a1ba2-29ac-11e6-9271-89c2f359a030.png)

**Comment by erhan-** [comment]
I have the same issue with a process that got created with the CREATE_SUSPENDED flag.

**Comment by erhan-** [comment]
@mrexodia  Thank you very much. Works good now :)
