### ISSUE TITLE
Wrong values in (edit dialogue box + hits counter)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#659]
- Try to edit a register's value for example, the `Bytes` text box will have a weirdly reversed order (big endian xD ).
![hh](https://cloud.githubusercontent.com/assets/11916365/15472680/b40b937a-20fc-11e6-8777-d5d21277a86b.jpg)

- Select a BP then press `Ctrl + E`, in the `Hit count` text box type for example 20,
it will be set to 32 !

- The calculator and the expression follower (`Ctrl + G`) are both fine, but i'm not sure if there are any more text boxes messed up, you might want to check all of them.

**Comment by torusrxxx** [comment]
Hit count is decimal.
Bytes is correct. 0x00000003 is stored in little endian as 03 00 00 00 in memory.

**Comment by wk-952** [comment]
Sure, the hits counter is decimal and hence why I mentioned it here, its text box treats input as hexadecimal which is a little bit confusing.

As for the edit dialogue box, it makes no sense to reverse the bytes order because this specific dialogue box is used when editing registers not mem locations, mem locations have a different dialogue box.

**Comment by torusrxxx** [comment]
I used hex originally but returned to decimal when I made the pull request. Breakpoint counter is intended for performance analysis, not for machine-readable, and it's assumed to be resetted only. Using decimal is more convenient in this case. You're not supposed to edit it to an arbitary value.
Bytes box should match byte order exactly with memory location, because registers can be read and write from memory. If you want big-endian then you can use Expression box.
