### ISSUE TITLE
Add cheat engine style auto assembler for code injection

### ISSUE THREAD

**Issue by wynick27** [x64dbg/x64dbg#729]
http://wiki.cheatengine.org/index.php?title=Cheat_Engine:Auto_Assembler
Need to parse label and functions and use assemble command. Shouldn't be too hard. Exec command is similar to this but without label support.

**Comment by mrexodia** [comment]
There is a plugin that does this, it's called multimate assembler. Take a
look at what they support (it's great).

**Comment by Spamm00r** [comment]
multimate assembler is ok, but it only does what x64dbg is already able to do.
What is missing is ChetaEngine's ability to automatically find, create and manage code caves. That's what is a pain in the ass to do in a a binary. Sure it is much easier to do that in memory compared to binary. But I was hoping to find a plugin that will do what CheatEngine does in Memory to binary.

I can add empty space in a binary as much as I want, but managing code caves for more complex code becomes challenging at some point. 

x64dbg is already very good, but I routinely am out of bytes because the next code section beginns in my code caves and was hoping to find a plugin that takes care of the code caves for me.

**Comment by ZehMatt** [comment]
> multimate assembler is ok, but it only does what x64dbg is already able to do. What is missing is ChetaEngine's ability to automatically find, create and manage code caves. That's what is a pain in the ass to do in a a binary. Sure it is much easier to do that in memory compared to binary. But I was hoping to find a plugin that will do what CheatEngine does in Memory to binary.
> 
> I can add empty space in a binary as much as I want, but managing code caves for more complex code becomes challenging at some point.
> 
> x64dbg is already very good, but I routinely am out of bytes because the next code section beginns in my code caves and was hoping to find a plugin that takes care of the code caves for me.

Just append a new section to the binary, this doesn't sound like something a debugger needs out of the box.

**Comment by Spamm00r** [comment]
> Just append a new section to the binary, this doesn't sound like something a debugger needs out of the box.

Yeah that's not the problem. The problem is keeping track of the code inside the codecave. CE takes care of where it writes the new code inside the code cave. You don't have to bother with it. That's the key advantage here. Right now I have to do that manually and it would be handy to have that option in x64.

**Comment by mrexodia** [comment]
This is most likely something you'll want to write a plugin for. Does CE patch the executable or is it also memory-only? Because if it's just in memory you should be able to VirtualAllocEx a range close to the executable and put all your code caves there. This is potentially a feature that could be added to https://github.com/m417z/Multiline-Ultimate-Assembler

**Comment by Spamm00r** [comment]
As far as I can see, CE only makes changes in Memory, that's why it can easily allocate as many code caves as are required. CE does not have x64dbg's apply/export patch or save modified file as exe feature. But CE's Auto Assemble is in my opinion superior to x64dbg'S one line assemble function. Combining this feature into x64dbg would make it so much better.

Problem with Mutiline assembler is that it hasn't been updated since 6 years. I understand that you can't add code caves in abinary as easily as CE does in memory. I'm happy to add the code cave at the end of the binary manually one time.  All it needs is to add an option to tell the plugin to start using a code cave inserted a specific address for example at the end of the binary and we would have replicated CE's auto assemble behavior.

**Comment by mrexodia** [comment]
You can already do what you want using multimate assembler. First you allocate your code cave, then assign a label to it, then tell multimate assembler to put the instructions at that label.

**Comment by Spamm00r** [comment]
Is this another plugin? [MUltimate Assembler v1.7](https://ramensoftware.com/multimate-assembler-v1-7)

Or is multiline a further development of multimate?

I can only find posts from 2012. That's older than multiline plugin.

**Comment by mrexodia** [comment]
It’s this: https://github.com/m417z/Multiline-Ultimate-Assembler

but yeah in 2017 this plugin worked and it will work on the latest x64dbg version just fine. The functionality is pretty finished, so no updates are necessary.

**Comment by cexer** [comment]
> You can already do what you want using multimate assembler. First you allocate your code cave, then assign a label to it, then tell multimate assembler to put the instructions at that label.

How do I allocate code cave in multimate assembler? I can't find a way. If there's a example code snippet, It would be great.

**Comment by cexer** [comment]
I'm happy to do it. I'll  submit a PR after confirm there are no serious bugs.
