### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#75]
---
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/75
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-04-19T21:11:21.146

**Comment by Ciantic** [comment]
:+1:

I'm trying to study explorer.exe, it has too many threads, even though I know which thread I should be looking at, it's difficult because I can't simply trace it.

I'm trying to get rid of FlashWindowEx behaviour of task switcher, in Windows 10 it's even more annoying, it shows flashing windows on all virtual desktops. And this can't just go on! It's driving me crazy. I hope to make a in-memory patch to get rid of whole feature, it should be as simple as stopping one message being handled.
