### ISSUE TITLE
Change Command Line goes wrong when the path contains dot and space

### ISSUE THREAD

**Issue by west036** [x64dbg/x64dbg#884]
For Example:
If the path likes "C:\aaa.10 bbb\ccc.exe -param". When Restart, the command line text changes to:
"C:\aaa.10 bbb\ccc.exe" bbb\ccc.exe" -param
It looks like the text after the space character being recognized as a param.

**Comment by mrexodia** [comment]
Are you using the 'InitDebug' command or the change command line option in the debug menu?

**Comment by Rulzy** [comment]
1. Start debugging a program like this path: "C:\aaa.10 bbb\ccc.exe" (the directory name contains dot and a space after dot).
2. Select menu "Debug -> Change Command Line", add some params to the end of command line.
3. Restart debugging the program, the program will get a incorrect command line. You also can select menu "Debug -> Change Command Line" to check it.

**Comment by mrexodia** [comment]
Alright that's clear. Most likely a bug with saving the command line.

**Comment by Rulzy** [comment]
Still not fixed?

**Comment by mrexodia** [comment]
It's not going to be fixed by me so consider fixing it yourself it's easy
enough to fix but I have no personal interest so why would I fix it?

Just see http://contribute.x64dbg.com and compile x64dbg that should get
you started.

Also we don't get paid 10k per customer for support, the project is open
source so if you want something the fastest way is to check if you can do
it yourself.

**Comment by mrfearless** [comment]
Ive a plugin that might help, but cant guarantee it will:
https://github.com/mrfearless/AutoCmdLine-Plugin-x86
https://github.com/mrfearless/AutoCmdLine-Plugin-x64

**Comment by mrexodia** [comment]
Is this still an issue?
