### ISSUE TITLE
String not beeing shown in comment section

### ISSUE THREAD

**Issue by Chandlr** [x64dbg/x64dbg#997]
related file (crackme):
https://mega.nz/#!YI9AGYSa!0thMIEqtNDDYQeX5iiUafyC-P8aT2Y9RVjsvmLYS7FQ

first its a pointer to string:
00E23094  45 30 E2 00 5E 30 E2 00 80 14 E2 00 60 2D E2 00  E0â.^0â...â.`-â.  
then the actual string:
00E23045  0D 0A 57 65 6C 6C 20 44 6F 6E 65 2C 20 49 27 6D  ..Well Done, I'm  
its not shown because of 0D 0A ?

**Comment by Chandlr** [comment]
Dont step just start it.. check string references and that string is there
but when following constant: 1373094
0137104A | 8B 85 94 30 37 01          | mov eax,dword ptr ss:[ebp+1373094]                    |
the pointer of that.. that shows string but not shown in comment section..

**Comment by wk-952** [comment]
@Chandlr 
It's not actually a bug, the string address is indeed stored in `0x1373094` (mine was `0x223094`, generally the address of the string is stored in RVA `0x3094`). But the instruction is actually accessing `EBP + 0x1373094` so the debugger is trying analyze the string pointed-to by `EBP + 0x1373094` not only `0x1373094`.
And since at the entry-point of the application (before stepping) the `EBP` register contains some values, you won't of course see the desired string.

To verify this yourself, at the entry-point of the application set `EBP` to 0,
so that the debugger tries to analyze the string point-to by `0 + 0x1373094`
![untitled](https://cloud.githubusercontent.com/assets/11916365/17876410/2fce2142-68da-11e6-84dc-1b21ab7790c8.png)
(hint: set `EBP` to 4 to see the bad boy's message!)

Or you can make use of the "dynamic comments" feature of the debugger to always see strings pointed-to by RVA `0x3094` (good boy) and RVA `0x3094 + 4` (bad boy).
Add the following as comments to the instructions:
__`string at RVA (0x3094) = {s:[(:$0x3094)]}`__
__`string at RVA (0x3094 + 4) = {s:[(:$0x3094+4)]}`__
![untitled2](https://cloud.githubusercontent.com/assets/11916365/17876692/ad6a50ba-68dc-11e6-8e7d-6861125e51fa.png)

**Comment by Chandlr** [comment]
thanks for verifying/clarifying :+1:
